### PR TITLE
Fixed icons color, message box, text color &  buttons misalignment  in the navbar Issue ! #735 & #777

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #735 & #777

When you select Dark mode these icons color &  "Travel" text color blends with the background color,
Issue Fixed -

https://github.com/user-attachments/assets/a2cb6066-c6c9-4ddf-87a4-b194a0d6f3b1

these buttons in the navbar of the repository's UI is not aligned properly, these buttons should maintain the same alignment like website logo "WordWise" alignment.
Issue Fixed -

https://github.com/user-attachments/assets/83a61dc5-1923-4838-83fd-9364943490a7

Add "Leave Comments" icon boxes border, text color for dark mode & add shadow properly, & These changes make this website so beautiful.
Issue Fixed -

https://github.com/user-attachments/assets/169fa3e0-e06d-4552-a4c4-5e46389e09b5

@ANSHIKA-26 @hiteashgupta1  
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@hiteashgupta1 PA merge it & please add the level 3 tag as I have solved the all issue properly & I did what you told me to do, I checked the live website and started it again from the beginning, also I had to fix a problem twice.. #775

**Comment by Subhajit-2023-44** [comment]
@hiteashgupta1 PA kindly upgrade the level 2 to 3

**Comment by Subhajit-2023-44** [comment]
@hiteashgupta1 PA kindly upgrade the level 2 to 3

I have solved the all three imp issues properly -
Icons color & "Travel" text color for dark mode
Misalignment of all buttons in the navbar
"Leave Comments" icon boxes border, text color for dark mode & add shadow properly

**Comment by hiteashgupta1** [comment]
@Subhajit-2023-44 Level 3 is for backend

**Pull request merged**
