### PR TITLE
Fixed the Navbar Successfully !!

### PR DESCRIPTION
**Pull request by AnujShrivastava01**
### Pull Request Checklist
#511 Done !!
- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

image

https://github.com/user-attachments/assets/b92441e8-8063-4783-bcaa-a65f08f24eea

### CODE REVIEW

**Comment by AnujShrivastava01** [comment]
@ANSHIKA-26 
Thankyou for Assigning ! 
Please give a level label and merge the pull request .

**Comment by ANSHIKA-26** [comment]
add a hover effect on elements on the navbar

**Comment by ANSHIKA-26** [comment]
show the login and signup pages working

**Comment by AnujShrivastava01** [comment]
> show the login and signup pages working

https://github.com/user-attachments/assets/833385d2-3ef1-4782-b4bd-7b4bc8f41c7b

**Comment by AnujShrivastava01** [comment]
@ANSHIKA-26 
Now please merge the pull request and a level2 label.

**Pull request merged**
