### PR TITLE
Improving User Experience: Key Design and Usability Issues in Sidebar Layouts

### PR DESCRIPTION
**Pull request by TornovDutta**
# Description
The popular tags design has been optimized for smaller screens with reduced font sizes and compact tag buttons. Social media icons are minimized while retaining their respective platform colors and hover effects. Spacing between elements is tightened for a cleaner look, and smooth transitions provide subtle interactivity. The layout uses flex-wrap to ensure responsiveness, allowing tags and icons to adjust seamlessly on smaller devices like mobile phones. This design enhances usability while maintaining a modern, minimalistic appearance.

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by TornovDutta** [comment]
# Sceenshot:


Before:
Screenshot 2024-10-08 124918

after:
Screenshot 2024-10-08 185743

**Comment by TornovDutta** [comment]
PR of #551 no issuse

**Comment by TornovDutta** [comment]
@ANSHIKA-26 please check the PR , and label the PR

**Comment by ANSHIKA-26** [comment]
decrease border size to just envelope the social media icon , in all icons the size of border is like an oval , it looks weird , either remove the border or fix it

**Comment by TornovDutta** [comment]
# screenshot:
Screenshot 2024-10-08 202214

**Comment by TornovDutta** [comment]
@ANSHIKA-26 please add the level label on the PR

**Comment by ANSHIKA-26** [comment]
just remove the border from social media icons altogether

**Comment by TornovDutta** [comment]
> just remove the border from social media icons altogether

The social media icons don't have any borders. Do you want to remove the colored circle from them, or should I fix it?

**Comment by TornovDutta** [comment]
Screenshot 2024-10-09 000845
 Those color circle??

**Comment by TornovDutta** [comment]
### Like this ?
Screenshot 2024-10-09 002221

**Comment by ANSHIKA-26** [comment]
yep , looks good

**Comment by ANSHIKA-26** [comment]
image
fix this , why is the color so light

**Comment by TornovDutta** [comment]
@ANSHIKA-26 Please check the PR

**Comment by TornovDutta** [comment]
### sceenshot:
Screenshot 2024-10-09 012726

**Comment by ANSHIKA-26** [comment]
twitter logo not visible in category page

**Comment by ANSHIKA-26** [comment]
image
why does it look like this on the blog page ?

**Comment by ANSHIKA-26** [comment]
@TornovDutta kindly fix the sidebar on all pages of the website , not just the homepage , this should have been covered by you yourself and not pointed out by me , kindly do the changes and make another PR

**Pull request closed without merging**
