### PR TITLE
Changed the scrollup button

### PR DESCRIPTION
**Pull request by likitha-kapu**
Issue: #1789 
Screenshot 2024-11-08 215327

### Pull Request Checklist

- [X ] I have added screenshots and videos to show before and after the working of my code.
- [ X] I have ensured that the screen size is set to 100% while making the video.
- [ X] I have synced the latest fork with my local repository and resolved any conflicts.
- [ X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ X] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by likitha-kapu** [comment]
@ANSHIKA-26 please review this pull request

**Comment by ANSHIKA-26** [comment]
image
this is what the button looks like on start writing page

**Comment by likitha-kapu** [comment]
> image this is what the button looks like on start writing page



> image this is what the button looks like on start writing page

Yeah ...I will change it

**Comment by likitha-kapu** [comment]
@ANSHIKA-26 check out once the pull request once...i have made changes
image

**Comment by ANSHIKA-26** [comment]
the aligned isnt uniform , the scroll to top button is liek this -
image
 in rest of the pages , where as in start writing page its like -
 
image

**Comment by likitha-kapu** [comment]
> the aligned isnt uniform , the scroll to top button is liek this - image in rest of the pages , where as in start writing page its like -
> 
> image

@ANSHIKA-26 I tried changing it but it is being overridden by other styles...I have tried out many ways

**Pull request merged**
