### PR TITLE
Update  fashion page:added different sections to the page

### PR DESCRIPTION
**Pull request by Ash914027**
issue numbr   #1501   Added different section to
changes page video
changes photo
![Screenshot 2024-10-28 105810](https://github.com/user-attachments/assets/75a0451e-a9b3-4cb6-a0f3-c419098dbd82)
![Screenshot 2024-10-28 105818](https://github.com/user-attachments/assets/52151789-9f33-41fc-bd3d-259784bd17d0)
![Screenshot 2024-10-28 105826](https://github.com/user-attachments/assets/fb2684db-e512-47d2-adea-cdf4e1ba3082)
![Screenshot 2024-10-28 105841](https://github.com/user-attachments/assets/011678f3-03fb-4fb1-87af-07989ea56095)


https://github.com/user-attachments/assets/e5ee4b7d-5b4d-464f-98e1-6724341e11ed

 earlier befire changes
![Monica_2024-10-28_10-34-34](https://github.com/user-attachments/assets/0ed79744-942d-4879-917d-6911c5568361)
                                                                                                                                                                                                          ### 1. Fashion Trends
- **Section Title**: Fashion Trends
- **Image**: 
  ![Fashion Trends Image](https://images.unsplash.com/photo-1614003139488-5e7d1c1b3e5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMjA3fDF8MHxpaG90by1wYWdlfHx8fGVufDB8fHx8MTYxNzIyNjI0NQ)
- **Explanation**: This section discusses the current fashion trends, highlighting the resurgence of vintage styles, eco-conscious fabrics, and bold colors. The image visually represents the dynamic nature of fashion.

### 2. Iconic Designers
- **Section Title**: Iconic Designers
- **Image**: 
  ![Iconic Designers Image](https://images.unsplash.com/photo-1568020900809-8f2c8a1d8c4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMjA3fDF8MHxpaG90by1wYWdlfHx8fGVufDB8fHx8MTYxNzIyNjI4Ng)
- **Explanation**: This section celebrates designers who have significantly impacted the fashion industry, such as Coco Chanel and Alexander McQueen. The image symbolizes the creativity and innovation these designers bring to fashion.

### 3. Sustainable Fashion
- **Section Title**: Sustainable Fashion
- **Image**: 
  ![Sustainable Fashion Image](https://images.unsplash.com/photo-1600585154360-0d7cb3

### CODE REVIEW

**Comment by Ash914027** [comment]
please accept my pull request and add hactoberfestaccepted label

**Comment by Ash914027** [comment]
@hiteashgupta1 please merge my pull request

**Comment by hiteashgupta1** [comment]
@Ash914027 kindly make navbar and footer like homepage

**Comment by hiteashgupta1** [comment]
Navbar is not visible in dark mode

**Comment by Ash914027** [comment]
ok add ing navbar

**Comment by Ash914027** [comment]
@hiteashgupta1 please check i updated the code merge my pull request

**Comment by hiteashgupta1** [comment]
You have not make it better and made irrelevant changes to ui of the fashion.html 
If you want to add only content to the page then don't make changes to ui if you couldn't make it better. We're closing this pr and make new pr and don't change the ui of navbar and footer.
Check the original page and then do changes

**Pull request closed without merging**
