### PR TITLE
Added the modified login & signup page under the profile icon

### PR DESCRIPTION
**Pull request by Mahima-2404**
### Pull Request Checklist

- [X ] I have added screenshots and videos to show before and after the working of my code.
- [X ] I have ensured that the screen size is set to 100% while making the video.
- [X ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X ] I understand that if any the above conditions are not met , my PR will not be MERGED .

#442 
Added the modified login & signup page under the profile icon .also  modified the navbar of every page.

https://github.com/user-attachments/assets/ba9b3bc2-bb21-4ba7-832b-47bdb15f6b88

Please merge it

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
fizes #442

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by AnujShrivastava01** [comment]
Issue in Navbar !!
When i am creating new issue bot is saying similar issue already exist .
So I am raising it here .
Pls assign this to me !
image

**Comment by shivam8112005** [comment]
i think someone uncommented old navbar code
let me handle this

**Comment by Mahima-2404** [comment]
@ANSHIKA-26 donee

**Pull request merged**
