### PR TITLE
Enhance README.md with animated line breaks and GIF emojis and icons

### PR DESCRIPTION
**Pull request by KhushiChauhan8**
### Summary
This pull request implements several enhancements to the README.md file, significantly improving its visual appeal and readability. 

### Related Issue
This pull request addresses issue #1471 .

### Changes Made
I have made the following changes:
- **Dynamic Animated Line Breaks**: Added visually distinct line breaks to create clear separations between sections, improving the overall flow.
- **GIF Emojis**: Replaced static emojis with animated GIF emojis in key sections to make the content more engaging and lively.
- **Enhanced Visual Hierarchy**:
  - Improved header styles to better organize content and enhance readability.
  - Ensured each section stands out while maintaining a clean and cohesive layout.

### Screenshots of Changes
Here are screenshots showcasing the enhancements made to the README.md file:
1. **Before Changes**:
   
Screenshot 2024-10-27 143655

   
2. **After Changes**:
  
Screenshot 2024-10-27 143502

### Request for Review
I would greatly appreciate your feedback on these improvements. Please let me know if any further adjustments are needed!

Thank you for considering this pull request! 🎉

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
1. you opened a PR without waiting for the issue to be assigned
2. i believe this is not you first time contributing to this repo , you do understand that you only have to start working on an issue after you have been assigned the issue !
3. closing PR and issue both since i dont require changes to readme

**Comment by KhushiChauhan8** [comment]
> 1. you opened a PR without waiting for the issue to be assigned
> 2. i believe this is not you first time contributing to this repo , you do understand that you only have to start working on an issue after you have been assigned the issue !
> 3. closing PR and issue both since i dont require changes to readme

Thank you for your feedback!  I want to clarify that I waited for the issue (#1471 ) to be assigned to me before submitting my PR. If there’s any misunderstanding or if you need further details, please let me know. I appreciate your guidance!

**Comment by KhushiChauhan8** [comment]
> 1. you opened a PR without waiting for the issue to be assigned
> 2. i believe this is not you first time contributing to this repo , you do understand that you only have to start working on an issue after you have been assigned the issue !
> 3. closing PR and issue both since i dont require changes to readme

Thank you for your feedback! 😊 I want to clarify that I waited for the issue (#1471) to be assigned to me before submitting my PR. If there’s any misunderstanding or if you need further details, please let me know. I appreciate your guidance!

**Comment by KhushiChauhan8** [comment]
Thank you for your feedback! 😊 I want to clarify that I waited for the issue (#1471) to be assigned to me before submitting my PR. If there’s any misunderstanding or if you need further details, please let me know. I appreciate your guidance!

**Comment by KhushiChauhan8** [comment]
Thank you for your feedback! 😊 I want to clarify that I waited for the issue (#1471) to be assigned to me before submitting my PR. If there’s any misunderstanding or if you need further details, please let me know. I appreciate your guidance!

**Pull request closed without merging**
