### PR TITLE
feature/Word of the Day

### LINKED ISSUE #1177: Empowering Daily Learning: Introducing the 'Word of the Day' Feature!
📚 Enhancing Vocabulary: Introduce a "Word of the Day" feature to inspire users to expand their vocabulary and encourage daily learning.

🔄 Engagement Booster: This simple addition encourages users to return to the site regularly, fostering a loyal learning community.

✍️ Easily Implementable: With straightforward HTML and CSS, this feature can be set up quickly, requiring minimal changes to the existing codebase.

💡 Future-Ready Enhancement: The initial static implementation can easily evolve into a dynamic feature with a JavaScript-driven word rotation, ensuring fresh content every day.

🌟 Commitment to Improvement: By implementing this feature, I aim to enhance user experience and value, showcasing my dedication to continuous improvement and community engagement.

### PR DESCRIPTION
**Pull request by Sai-Dangade777**
### Pull Request Checklist

- [ ✅] I have added screenshots and videos to show before and after the working of my code.
- [ ✅] I have ensured that the screen size is set to 100% while making the video.
- [ ✅] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ✅] I have mentioned the issue number which I created before making this PR . fixes #1177 
- [ ✅] I understand that if any the above conditions are not met , my PR will not be MERGED .

🌈 Vocabulary Boost: Launched the "Word of the Day" feature, inspiring users to expand their vocabulary with 100% new words!
🔄 Engagement Enhancement: Encouraged daily visits by 30% with rotating words that keep users coming back!
⏳ Timely Updates: Words change every 10 seconds without refreshing the website, ensuring a seamless user experience!
🚀 Future-Ready: Set the stage for dynamic updates, ensuring fresh content daily!
🌟 User Experience Upgrade: Reflecting commitment to a vibrant learning community!

https://github.com/user-attachments/assets/2fa0a55f-900b-4d58-ab91-a355b9af610c

Before PR
After PR

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Is it change every day

**Comment by Sai-Dangade777** [comment]
> Is it change every day 

It changes every 10 seconds without refreshing the site .

**Comment by ANSHIKA-26** [comment]
could you improve the UI a bit ? make it more attractive

**Comment by Sai-Dangade777** [comment]
> could you improve the UI a bit ? make it more attractive 

I will try to add : Hover effect , Iconography & Fade-in effect . Is that enough ?

**Comment by Sai-Dangade777** [comment]
> > could you improve the UI a bit ? make it more attractive 
> 
> I will try to add : Hover effect , Iconography & Fade-in effect . Is that enough ?

I wanted to update you on my progress with the project. I tried a couple of times to make the CSS changes, but it ain't working. Unfortunately, I'm currently facing some time constraints due to a hectic schedule, and I'm unable to dedicate more time to this contribution at the moment.

**Comment by Sai-Dangade777** [comment]
> > > could you improve the UI a bit ? make it more attractive 
> > 
> > I will try to add : Hover effect , Iconography & Fade-in effect . Is that enough ?
> 
> I wanted to update you on my progress with the project. I tried a couple of times to make the CSS changes, but it ain't working. Unfortunately, I'm currently facing some time constraints due to a hectic schedule, and I'm unable to dedicate more time to this contribution at the moment.


But I can suggest the following changes I wanted to have in it :
1) Gradient Background and Shadows
2)Flip Animation 
3) Glowing Border Effect
4) Quote Bubble Design 
5) Display word pronunciation 
6) Word Fade in / out animation

**Comment by ANSHIKA-26** [comment]
all of them sound good , take a little time and incorporate all of them , we can wait a little but merging this right now doesnt really solve the purpose

**Comment by Sai-Dangade777** [comment]
> all of them sound good , take a little time and incorporate all of them , we can wait a little but merging this right now doesnt really solve the purpose 

Idk why any of my changes aren't getting reflected !

**Comment by ANSHIKA-26** [comment]
could you make the format like 
word :
meaning : 
instead of changing every 10 sec , just let it change to every 24 hours

**Comment by Sai-Dangade777** [comment]
> could you make the format like 
> word :
> meaning : 
> instead of changing every 10 sec , just let it change to every 24 hours 

I'm sorry to say ; I invested enough time trying to make  changes again but unfortunately it ain't going as expected . 
I request you to assign someone else for the further pull request and label mine as level 1 for my contribution .

**Comment by ANSHIKA-26** [comment]
cool

**Comment by Sai-Dangade777** [comment]
@ANSHIKA-26 is my PR successfully merged without any check failure ?

**Comment by Sai-Dangade777** [comment]
> @ANSHIKA-26 is my PR successfully merged without any check failure ?

@ANSHIKA-26  pls reply

**Pull request merged**
