### PR TITLE
added uniform footer to my reading list page

### LINKED ISSUE #1788: footer on my reading list page is different then other pages
**Describe the bug**
The footer on the Reading List page has a different appearance or behavior compared to the footer on other pages.

**To Reproduce**
1. Go to the Reading List page.
2. Scroll down to the footer section.
3. Observe the footer’s appearance and functionality.

**Expected behavior**
The footer on the Reading List page should have the same style and functionality as the footer on other pages for consistency.

**Screenshots**
Screenshot 2024-11-08 200231

**Additional context**
The issue may be due to different CSS styles applied specifically to the Reading List page.
Check if there are any unique classes or IDs used for the footer on this page, or if there is any JavaScript that might be affecting the footer's appearance.

### PR DESCRIPTION
**Pull request by shivam8112005**
### Pull Request Checklist
Fixes #1788 
- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

Before:
Screenshot 2024-11-08 200231
After:
Screenshot 2024-11-14 000357

### CODE REVIEW

**Comment by shivam8112005** [comment]
@ANSHIKA-26 canyou review this?

**Comment by ANSHIKA-26** [comment]
@shivam8112005 i can , but the program is already over and the results are out as well , so you wont be getting any points for it

**Comment by shivam8112005** [comment]
@ANSHIKA-26 yes i know that i am just doing for practicig only

**Comment by ANSHIKA-26** [comment]
nice , great job , keep it up , i am merging this without any labels then

**Pull request merged**
