### PR TITLE
Updated overlapping of login and signup popup forms

### LINKED ISSUE #1467: [ Bug ] : Updated overlapping of login and signup popup forms
### Issue Description

When the signup popup is closed, the previously opened login popup reappears unexpectedly. This occurs due to improper state handling between the two popups. Users expect only one popup to be active at a time, but the login popup reopens unintentionally. This bug disrupts the user experience and needs a fix to ensure smooth popup transitions. The solution involves updating event handling to close the current popup before opening a new one.

@ANSHIKA-26 
Pls assign me this issue and give me level3 and labels like gssoc-extd,hacktoberfest-accepted.

### PR DESCRIPTION
**Pull request by ygowthamr**
### Pull Request Description

Fix #1467

- **Issue:** Fixes a bug where closing the signup popup displays the previously opened login popup.
- **Changes Made:** Updated logic to ensure only one popup is displayed at a time.
- **Improvements:** Enhanced event handling to close the current popup before opening a new one.
- **Testing:** Verified that the functionality works correctly for both login and signup popups.
- **Review:** Please check the changes for any further improvements.

@ANSHIKA-26 
Pls review the code and assign me, Also give me labels like level2,gssoc-extd,hacktoberfest-accepted.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
This does not have issue no i have directly kept PR request

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Now added issue number pls assign me the issue and review this pr and merge it

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Pls merge this pr also

**Pull request merged**
