### PR TITLE
Api for blog post and Mongodb connection issue #546

### PR DESCRIPTION
**Pull request by AyushSharma72**
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

i created an Api which let the user to post the blogs along with the image 

database storage of data 
Screenshot (178)

frontend
Screenshot (177)

please add level3  and gssoc-ext before merge

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by AyushSharma72** [comment]
> issue number ?

#456

> issue number ?

#546

**Comment by AyushSharma72** [comment]
> issue number ?

#546

**Comment by AyushSharma72** [comment]
> sync fork

ok

**Pull request merged**
