### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Ek-ta-bharti**
### Pull Request Checklist

- [ ] I have added screenshots and videos to show the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.

### CODE REVIEW

**Comment by Ek-ta-bharti** [comment]
ok

**Comment by ANSHIKA-26** [comment]
resolve merge conflicts

**Comment by hiteashgupta1** [comment]
@Ek-ta-bharti what changes are you doing kindly share relevant screenshots and information

**Comment by hiteashgupta1** [comment]
This branch has conflicts resolve them

**Pull request closed without merging**
