### PR TITLE
Add Star rating widget done ! #1045

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature Star rating widget - #1045

Done -

https://github.com/user-attachments/assets/2460a898-28f4-4e15-97db-9df3b3709647

Before -
Screenshot 2024-10-17 002119
Screenshot 2024-10-17 002128

After - 
Screenshot 2024-10-17 002141
Screenshot 2024-10-17 002149

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
conflicts

**Comment by Subhajit-2023-44** [comment]
> conflicts

Screenshot 2024-10-17 005834

**Comment by ANSHIKA-26** [comment]
make a new PR ,its not even allowing me to resolve :(

**Comment by Subhajit-2023-44** [comment]
> make a new PR ,its not even allowing me to resolve :(

Okay 😢😭

**Comment by Subhajit-2023-44** [comment]
> make a new PR ,its not even allowing me to resolve :(

Conflicts reason - someone working on the same files... 😢

**Pull request closed without merging**
