### PR TITLE
Made UI changes

### PR DESCRIPTION
**Pull request by Slambot01**
@ANSHIKA-26 ,You have assigned me issue #47 & I was working on this issue for two days and today this issue was closed by someone.I am attaching the video of my work for the reference .Can you please consider this PR and merge it in your Repo.

https://github.com/user-attachments/assets/c6b655d3-6d04-47f5-90b2-6326d7febbf0

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
This has conflicts kindly resync

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26 Look into this

**Comment by Slambot01** [comment]
Conflicts resolved @hiteashgupta1 .

**Comment by ANSHIKA-26** [comment]
@Slambot01 hey , firstly GREAT JOB ! the UI is pretty impressive !

**Comment by ANSHIKA-26** [comment]
but I really do prefer the UI and color palette the website is having right now , your Ui is simple amazing , but differs from the theme of wordwise a lot , im sorry but i wont be merging this PR , kindly try to communicate the changes you are aiming for while working with the issue , would have saved you a lot of hardwork , im really sorry but I cannot change the whole theme of the website in order to merge 1 PR

**Comment by ANSHIKA-26** [comment]
> @ANSHIKA-26 Look into this

thanks !

**Comment by ANSHIKA-26** [comment]
@Slambot01 i would suggest you to use the Ui as a template for some other web app , it wont go waste that way , thank you ! :)

**Comment by Slambot01** [comment]
@ANSHIKA-26 , I understand that you prefer the previous UI, but I believe the current version has only a few minor changes, particularly in the layout and color scheme. These adjustments were made with the intention to enhance the overall experience without deviating too much from the original design.

I would kindly request you to reconsider this version, as I believe it maintains the essence of the previous UI while adding subtle improvements. Your feedback is important, so I'd be happy to discuss further if needed.

**Comment by Slambot01** [comment]
@ANSHIKA-26  @hiteashgupta1  , I understand that you prefer the previous UI, but I believe the current version has only a few minor changes, particularly in the layout and color scheme. These adjustments were made with the intention to enhance the overall experience without deviating too much from the original design. I've also invested a significant amount of time in making these improvements to ensure they align with the project goals.

I would kindly request you to reconsider this version, as I believe it maintains the essence of the previous UI while adding subtle improvements. Your feedback is important, so I'd be happy to discuss further if needed.

**Comment by hiteashgupta1** [comment]
@Slambot01 You have done a great job 
But we can't go further with this UI as it is not preferable for the website. You can work with this current UI and can make changes if you want

**Pull request closed without merging**
