### PR TITLE
Converted_Images_to_WebP_for_Better_Optimization

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes** #1135 

- Converted all relevant images from formats like PNG and JPEG to WebP for better optimization and performance.
- WebP offers better compression without significant quality loss, which helps in reducing file sizes and improves page load speed.

**Changes:**

- Replaced existing image formats (JPEG, PNG) with WebP versions.
- Updated image references in HTML files to reflect the new WebP file paths.
- Verified that images render correctly in browsers that support WebP.

**Testing:**

- Verified on multiple browsers (Chrome, Firefox, etc.) to ensure proper image rendering.
- Ensured fallback mechanisms are in place for browsers that do not support WebP (if needed).

_**Note**_:  Add gssoc-ext with level3, hacktoberfest-accepted labels! I think this PR deserves level3 label. Please add it i have worked hard to do this! 

@ANSHIKA-26

### CODE REVIEW

**Comment by smog-root** [comment]
@harshbhar0629 please upgrade it to level3.

i really worked hard for it!

**Comment by ANSHIKA-26** [comment]
?

**Comment by ANSHIKA-26** [comment]
> @harshbhar0629 please upgrade it to level3.
> 
> i really worked hard for it! and there will be no space between level!

you tagged the wrong person but yea you did change a lot of links everywhere , kindly fix the way its looking , will upgrade to level3

**Comment by smog-root** [comment]
> 
> image
> ?

Which Page??

**Comment by smog-root** [comment]
Everything is working properly!! @ANSHIKA-26

Proof:-(screen recording)!

https://mega.nz/file/wG8RgCxK#UHMunSiiaPSVpvdyo7mfMelcBA6myGSsSvdcSbijqpk

i think the error is on you'r end!!

**Comment by ANSHIKA-26** [comment]
okay , resolve conflicts

**Comment by ANSHIKA-26** [comment]
on clicking on contact_us it redirects us to a completely new navbar , with different hover effect and no light-dark mode , why ?

**Comment by smog-root** [comment]
@ANSHIKA-26 I didn't edit anything other than images!!! Check the code!! 

I think it is coming because of other PR merges!

**Comment by smog-root** [comment]
> on clicking on contact_us it redirects us to a completely new navbar , with different hover effect and no light-dark mode , why ?

Send me a screen recording!!!

**Comment by smog-root** [comment]
There is no error or anything! i don't understand. why are you getting errors!

**Proof**(screen recording)!: contact_us.html

https://mega.nz/file/sLVWVRJB#vNASGVvQg30G1egPFDgWnZhWbpNbHKgZqn6gsh2VcWk

@ANSHIKA-26

**Comment by smog-root** [comment]
Everything is working perfect! Stop finding error! and Merge it!

Everything will work as usual!

**Comment by ANSHIKA-26** [comment]
ok , sync fork

**Comment by smog-root** [comment]
@ANSHIKA-26 wait a sec I will create a new PR! The conflicts are long!

**Comment by smog-root** [comment]
i'm closing this PR because of lot of conflicts!

I have Opened new PR #1230 MERGE IT!!! @ANSHIKA-26

**Pull request closed without merging**
