### PR TITLE
Added Search functionality

### PR DESCRIPTION
**Pull request by Varsha-1605**
# Fixes: #622 
Description:
Added Search Functionality to search the blogs based on the title.

Screenshots:
image

image

image

### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
This branch has conflicts that must be resolved

**Comment by hiteashgupta1** [comment]
@Varsha-1605 remove search blog from home index.html don't add in index.html

**Comment by Varsha-1605** [comment]
removed search bar from index.html:
image

**Comment by hiteashgupta1** [comment]
Add dark light mode in navbar

**Comment by hiteashgupta1** [comment]
Add dark light mode in navbar 
Kindly don't do any changes in navbar

**Comment by Varsha-1605** [comment]
@hiteashgupta1 It is already there in the body but not in the nav bar in the main branch, so I have done my work by adding search functionality as per the issue raised.

**Comment by hiteashgupta1** [comment]
@Varsha-1605 you don't have done any changes in index.html

**Comment by hiteashgupta1** [comment]
I'll delete the changed index.html file 
I'll only merge blog.html file

**Comment by hiteashgupta1** [comment]
Kindly make new pr and do changes only to that file

**Comment by Varsha-1605** [comment]
@hiteashgupta1 I have removed search bar from index.html that's why i have send you the screenshots of work.

**Pull request merged**
