### PR TITLE
deleted and arranged images in the repo

### PR DESCRIPTION
**Pull request by sakshamsaraf23**
this solves #269 
before
Screenshot 2024-10-05 141939
after:
Screenshot 2024-10-05 143426
i also changed the location of "untitled design" from repo to the images folder in the so also have to change the location in the readme file :
before
Screenshot 2024-10-05 143850
after
Screenshot 2024-10-05 143950

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
What issue are you trying to solve

**Comment by hiteashgupta1** [comment]
This branch has conflicts that must be resolved

**Comment by sakshamsaraf23** [comment]
sir the visiblity of the tags of the nav
before:
Screenshot 2024-10-05 141416
after:
Screenshot 2024-10-05 151738

**Comment by hiteashgupta1** [comment]
But it has conflicts kindly resync

**Comment by sakshamsaraf23** [comment]
sure sir

**Pull request merged**
