### PR TITLE
Added Google Signin Frontend

### PR DESCRIPTION
**Pull request by NK-Works**
### Pull Request Checklist
Solved: #375 

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

Video:

https://github.com/user-attachments/assets/b6c762d4-46f5-4a55-9f65-c43e9a7fd2d5

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
resolve merge conflict

**Comment by NK-Works** [comment]
@ANSHIKA-26 done...

**Comment by ANSHIKA-26** [comment]
there are still some conflicts

**Comment by NK-Works** [comment]
resolved again :(

**Comment by NK-Works** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
sure , thanks for informing !

**Pull request merged**
