### PR TITLE
Social media share feature

### PR DESCRIPTION
**Pull request by aditiverma-21**
Added few features

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
This branch has conflicts that must be resolved

**Comment by hiteashgupta1** [comment]
This branch has conflicts resolve them

**Comment by aditiverma-21** [comment]
Resolved conflicts

**Comment by aditiverma-21** [comment]
@ANSHIKA-26 Could you please review the pull request when you get a chance? Thanks!

**Comment by ANSHIKA-26** [comment]
@aditiverma-21 kindly DO NOT IGNORE THE PR CHECKLIST , it clearly states that you should add screenshots and explain what changes you have done

**Comment by hiteashgupta1** [comment]
Share the relevant screenshots of the features you have added

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by aditiverma-21** [comment]
Thank you for merging the commits. I will try to add more attractive styles for the same.

**Comment by hiteashgupta1** [comment]
@aditiverma-21 keep contributing

**Comment by aditiverma-21** [comment]
Yess

**Comment by aditiverma-21** [comment]
hello @hiteashgupta1 can you please add more labels to this ?

**Comment by aditiverma-21** [comment]
@ANSHIKA-26 @hiteashgupta1 I did the task but never got the labels can you please answer

**Pull request merged**
