### PR TITLE
changed Navbar design

### LINKED ISSUE #431: Enhance Navbar UI Design
**Describe the bug**
The current navbar lacks an attractive UI design. The navigation links are misaligned, and the hover effects on the navigation links is not that clean which impacts the overall look and feel of the website.

**To Reproduce**
1. Go to the homepage.
2. Hover over any navigation link.
3. Notice that hover effect is very old fashion.

**Expected behavior**
The navbar should feature an attractive UI with visually appealing transitions, properly aligned links, and a clean Hover effect  to provide a more engaging user experience.

**Screenshots**
Screenshot 2024-10-06 212825

**Additional context**
This issue affects the visual appeal and usability of the website. Enhancing the navbar with a more attractive and cohesive design would significantly improve the user interface and overall user experience.

### PR DESCRIPTION
**Pull request by shivam8112005**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

fixes #431 
before:
Screenshot 2024-10-06 212825
after:

https://github.com/user-attachments/assets/5cdae867-e0d7-4a75-bb9b-69ea71997167

### CODE REVIEW

**Comment by shivam8112005** [comment]
please let me know if there is any  problem coz i was getting many merge conflicts😅

**Comment by ANSHIKA-26** [comment]
try syncing the fork once ? also the logo on the left hand side needs to be removed

**Comment by ANSHIKA-26** [comment]
just confirm from your end if all the features present in the hosted link are intact or not ? like are all the other pages opening and working fine ?

**Comment by ANSHIKA-26** [comment]
also , Great job following the checklist ! thank you !

**Comment by shivam8112005** [comment]
ohk wait let me check it once

**Comment by shivam8112005** [comment]
yes its working properly

**Comment by ANSHIKA-26** [comment]
sync fork and remove svg as mentioned in the review

**Comment by shivam8112005** [comment]
i have created one more pr with removed svg logo

**Pull request closed without merging**
