### PR TITLE
Features

### PR DESCRIPTION
**Pull request by pinakviramgama**
--button changes
--hover changes
--some additional changes

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Please apporve my code

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by pinakviramgama** [comment]
Actually sir/mam i added some features to the site, if you need i will resolve some issues too.

**Comment by ANSHIKA-26** [comment]
https://github.com/ANSHIKA-26/WordWise/issues/435

go through this

**Pull request closed without merging**
