### PR TITLE
Update  nav bar and whole page

### PR DESCRIPTION
**Pull request by Ek-ta-bharti**
The design is fully responsive with no conflicts anywhere. I've shared the link, so you can check it yourself. Additionally, all screenshots and videos are working perfectly. 

https://github.com/user-attachments/assets/1a0704d3-ea78-4ba6-a153-aa0cfbf8c589

https://github.com/user-attachments/assets/7e957b9d-cee6-4415-8c7d-a54cba7bde12

Screenshot 2024-10-06 190958
Screenshot 2024-10-06 191032

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by hiteashgupta1** [comment]
Kindly show full website video of changes

**Comment by hiteashgupta1** [comment]
And also show issue raise

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Pull request closed without merging**
