### PR TITLE
start navber fixed

### PR DESCRIPTION
**Pull request by PATILYASHH**
### Start navbar fixed

image

### Pull Request Checklist

- [x] I have added screenshots and videos to show the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.

issue no : #171

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
can you share a video of your localhost , showing the changes you have done ?

**Comment by ANSHIKA-26** [comment]
sure

**Comment by PATILYASHH** [comment]
@ANSHIKA-26 

https://word-wise-peach.vercel.app/

**Comment by hiteashgupta1** [comment]
This branch has conflicts resolve them

**Comment by PATILYASHH** [comment]
Oky

**Comment by hiteashgupta1** [comment]
Kindly resync fork

**Pull request closed without merging**
