### PR TITLE
Improved the Navbar U.I.

### PR DESCRIPTION
**Pull request by aditya07389**
# hey @ANSHIKA-26 ,

i have completed adding the changes that i had proposed (issue number #242 ).

# before the site looked like this : 
image
# after i made the navbar changes it looks like this:
image

Its responsive now , also there's a better hover effect. it turns into light brown (more precisely a shade of beige when you hover over it with the mouse)

Thankyou for providing me this opportunity to contribute to your project .  
# Also  can you please tell me how will i know whether this pull request is approved , also this will be added to my score right ?

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Kindly resync and resolve conflicts

**Comment by hiteashgupta1** [comment]
And make video how responsiveness working

**Comment by aditya07389** [comment]
hey @hiteashgupta1 ,

i am seeing these issues :

image

and this :

image

can you please tell me how to resolve it ? this is my first time.

**Comment by hiteashgupta1** [comment]
Resync the files

**Review by ANSHIKA-26 — CHANGES_REQUESTED** [review]

**Comment by aditya07389** [comment]
@hiteashgupta1 
@ANSHIKA-26  
on it guys

**Comment by aditya07389** [comment]
@hiteashgupta1 i have resolved the merge conflicts , please review 

Also here is the video to show you the responsiveness of the navbar:

https://github.com/user-attachments/assets/0b6ec3c6-d264-4521-b0da-5518d795045d

I hope you aprove my changes

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by aditya07389** [comment]
hey @hiteashgupta1 can you please add level-2 label to this P.R. ? it was added on the issues section but in here level-1 has been assigned

**Comment by aditya07389** [comment]
hey @ANSHIKA-26 can you please add level 2 tag as mentioned in the issues section for this , thankyou.

**Comment by ANSHIKA-26** [comment]
@aditya07389 great job ! thanks a lot for your contribution !

**Pull request merged**
