### PR TITLE
Improved Newsletter section design

### PR DESCRIPTION
**Pull request by Subham1**
### Pull Request Checklist
**ISSUE** #1074 
I redesigned the newsletter section to make it more responsive, ensuring it looks great on all screen sizes, which improves usability for both mobile and desktop users. I adjusted the size and spacing to create a more compact and visually appealing appearance. Additionally, I added hover text to enhance user interaction 

image

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by Subham1** [comment]
@hiteashgupta1 pls review my code

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by ANSHIKA-26** [comment]
Thank you for your contribution! The image you added is a bit too large for the newsletter and affects the overall layout. Could you resize it or consider using a smaller, more subtle image that fits the design better? This way, it won’t distract from the content. Looking forward to your updated changes!

**Comment by ANSHIKA-26** [comment]
closing PR due to lack of response

**Pull request closed without merging**
