### PR TITLE
changes in design and alignment in contact us section, in newsletter section and in FAQ section

### PR DESCRIPTION
**Pull request by eshitatalukdar08**
#698 
Hello @ANSHIKA-26,

I have made the necessary changes:

**CONTACT US PAGE:**
1. Adjusted the spaces and alignments.
2. Added hover effects and smooth transitions to the submit button.
3. Selected a related image to enhance the appearance of the page.
4. Modified additional effects, including padding, margin, and shadows.

**NEWSLETTER SECTION:**
1. Redesigned the layout by updating the border, padding, border radius, and shadows.
2. Previously, the newsletter section lacked updates in dark mode, so I made changes to the background color and text color.

**EXTRA: FAQ SECTION:**
While I was making these changes, I noticed that the FAQ section did not have hover effects in either light or dark mode. I added some enhancements for that.

I hope you like the changes. Please accept this pull request. Have a great day!

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
conflicts

**Comment by eshitatalukdar08** [comment]
I cannot understand can you please elaborate

**Comment by ANSHIKA-26** [comment]
fix merge conflicts

**Comment by eshitatalukdar08** [comment]
Okay I will do this within tomorrow

**Comment by ANSHIKA-26** [comment]
@eshitatalukdar08 hey , the longer you wait , the more conflicts , kindly resolve them

**Comment by eshitatalukdar08** [comment]
I am actually not able to understand where I can see the conflict and what is causing the conflict

**Comment by eshitatalukdar08** [comment]
Like what is the process of resolving and how to identify the conflicts.Can you please help?

**Comment by ANSHIKA-26** [comment]
Identify the conflicts: Git will show you the files and lines where the conflict occurred when you try to merge or pull changes.
Open the file: Look for conflict markers like:
markdown
<<<<<<< HEAD
// Your changes
=======
// Other branch's changes
>>>>>>> branch-name

Decide which changes to keep: Review the conflicting changes and choose whether to keep one version or combine both.
Remove the conflict markers: Once you've decided which changes to keep, delete the <<<<<<<, =======, and >>>>>>> markers.
Stage the resolved files: Use git add <file> to stage the resolved files.
Complete the merge: Run git commit to finish the merge after resolving conflicts.

**Comment by ANSHIKA-26** [comment]
kindly resync and refork , then make a NEW PR , that will help too , your fork might be very old !

**Comment by eshitatalukdar08** [comment]
Okay can I submit it tomorrow then?

**Comment by eshitatalukdar08** [comment]
Thank you @ANSHIKA-26 , I was clueless until no

**Pull request closed without merging**
