### PR TITLE
added the good looking theme toggler, and better navigation bar issue#33

### PR DESCRIPTION
**Pull request by KajalDeore04**
added the good looking theme toggler, and better navigation bar
 issue #33

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
hey , there are some merge conflicts with your file index.html , kindly sync fork and do the needful , also please attach images of the changes you have done with the PR

**Comment by KajalDeore04** [comment]
worked on the navbar and toggler..
Screenshot 2024-10-02 163229

i dont see any conflict on my side. just the one thing that's causing problem is the header navbar that already existed. i do not have permission to make overwrite it so, look into it. when i tried to remove that previous existing navbar it was causing conflicts

**Review by hiteashgupta1 — DISMISSED** [review]

**Comment by KajalDeore04** [comment]
Screenshot 2024-10-02 224844
yes i have checked all the files and everything looks fine

**Comment by ANSHIKA-26** [comment]
could you show the images of light theme as well ?

**Comment by KajalDeore04** [comment]
allow me some time for that please

**Comment by KajalDeore04** [comment]
Screenshot 2024-10-02 235130

**Comment by KajalDeore04** [comment]
do i not have write access to index.html and style.css? why is there a conflict in the whole file

**Comment by hiteashgupta1** [comment]
Changes are good but there are some conflicts in files kindly check

**Comment by KajalDeore04** [comment]
Tbh, I just I don't know how to resolve them now because I did literally everything but the file shows the conflict and write access error.

**Comment by ANSHIKA-26** [comment]
hey @KajalDeore04 kindly sync fork and then try

**Comment by KajalDeore04** [comment]
Okay

**Pull request closed without merging**
