### PR TITLE
Adding multi language support system✨ 

### LINKED ISSUE #1118: Adding multi language support system✨
I want to add multi language support system to the website which can help us understand in their native language.

@ANSHIKA-26 can you assign me this issue.

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
Fixes #1118 

@ANSHIKA-26 can you review this please.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@ANSHIKA-26 can you review this please.

**Comment by ANSHIKA-26** [comment]
I'm closing this PR because it goes against two important guidelines:

You didn’t check for duplicate issues before starting work, and someone else had already raised this issue.
(#1044)
You didn’t wait to be assigned the issue before working on it, which is clearly stated in the rules.
Please follow the contribution guidelines next time. Working without checking or being assigned only creates confusion and wastes effort. Be sure to follow the process going forward.

**Comment by T-Rahul-prabhu-38** [comment]
im sorry , u assigned me the level so i thought i can work on it.

**Comment by ANSHIKA-26** [comment]
1. no one assigned you any level
2. the tags of ggsoc and hacktoberfest are added be default to any issue that opens via a bot  , i didnt assign you anything

**Pull request closed without merging**
