### PR TITLE
darkMode toggle created!

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
@ANSHIKA-26 

https://github.com/user-attachments/assets/824c6640-496d-4bf2-8a23-78efb8470ba8

the darkmode is functioning well for all the pages.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
can u assign the level as well.

**Comment by T-Rahul-prabhu-38** [comment]
thank you for level2 , but it was very hard to integrate can i get a level 3 please :).

**Comment by hiteashgupta1** [comment]
@T-Rahul-prabhu-38 can you refork from latest repo and again add this feature

**Comment by T-Rahul-prabhu-38** [comment]
what about the levels as that was lvl 2 and this was level 1

**Comment by T-Rahul-prabhu-38** [comment]
sureee ill do that

**Pull request merged**
