### PR TITLE
Added Feature Voice-to-Text Blogging and AI-Powered Writing Assistant

### PR DESCRIPTION
**Pull request by UTkARsh-RaJ01**
#702  Feature addition of Voice-to-Text Blogging and AI-Powered Writing Assistant
I have added the features mentioned above.
To run these first you have to install the requirements mentioned in requirements.txt.
Then run the app.py and then run index.html.

https://github.com/user-attachments/assets/2961e830-e85b-4550-8d3e-1af95211b7bf

https://github.com/user-attachments/assets/45467c1e-0490-4711-94c7-25cfc2079467

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
great job , sync fork

**Comment by UTkARsh-RaJ01** [comment]
I synced the fork,should In give another pull request

**Comment by hiteashgupta1** [comment]
No need for another pr
Sync fork

**Comment by UTkARsh-RaJ01** [comment]
@hiteashgupta1 
I have successfully synced my fork,Will this now allow the pull request to be merged, or are there any additional steps required?

**Comment by hiteashgupta1** [comment]
Your fork is outdated 
Kindly refork and resync

**Comment by UTkARsh-RaJ01** [comment]
@hiteashgupta1 
image
It is showing updated

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by UTkARsh-RaJ01** [comment]
@hiteashgupta1 @ANSHIKA-26 Thank you for guiding

**Pull request merged**
