### PR TITLE
updated-contact-form

### PR DESCRIPTION
**Pull request by NK-Works**
### Pull Request Checklist
Closes: #745
Image of the updated form:
image
image

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
This branch has conflicts that must be resolved

**Comment by NK-Works** [comment]
@ANSHIKA-26 resolved

**Comment by ANSHIKA-26** [comment]
great , sync fork

**Comment by NK-Works** [comment]
synced... also the contact us form and the feedback form both are the same just to let u know...
hence by changing the contact us form feedback form is also changed...
wrote this bcz saw another pull for the same issue..

**Comment by NK-Works** [comment]
just checked the pull...
it seems he created a new form for feedback so it is changed now

**Pull request merged**
