### PR TITLE
Removed Profile Bugs

### PR DESCRIPTION
**Pull request by NK-Works**
### Pull Request Checklist
image
Now the profile page doesn;t show up when the user is not logged in

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Is it shows after login

**Comment by hiteashgupta1** [comment]
Mention issue number

**Comment by ANSHIKA-26** [comment]
even after logging in , we cannot see the profile customized according to user , kindly add a working video of the same

**Comment by NK-Works** [comment]
@ANSHIKA-26 @hiteashgupta1 you guys do know that the login/signup backend is not connected the frontend in this project as of yet...?
I have given the JS of what should happen once `ACTUAL` login happens...
image

Now here's the video of why I am saying that the backed login for the login and signup is not connected to the frontend... 
https://github.com/user-attachments/assets/6b3897a1-4174-4231-8483-1b98f83480db

**Comment by NK-Works** [comment]
Also if you want i can solve this issue... by actually connecting the frontend and backend as well

**Comment by NK-Works** [comment]
closes: #1693

**Comment by ANSHIKA-26** [comment]
> Also if you want i can solve this issue... by actually connecting the frontend and backend as well

go ahead

**Comment by NK-Works** [comment]
@well do I create a new issue for that? 😅

**Comment by ANSHIKA-26** [comment]
just solve it in this issue , mention issue number for old issue , will upgrade level for this PR

**Comment by NK-Works** [comment]
Closes Issue: #1693 

https://github.com/user-attachments/assets/ca23723d-7214-4070-8ecb-f2be67d5750d

I have added the complete logic for the backend connection and also I have implemented the logic for the logout as well...
Now i am going to create another issue to fetch the user data fromt he database and show it in the profile page rather the current static plan

**Comment by ANSHIKA-26** [comment]
> Closes Issue: #1693
> 
>  Untitled.video.-.Made.with.Clipchamp.mp4 
> I have added the complete logic for the backend connection and also I have implemented the logic for the logout as well... Now i am going to create another issue to fetch the user data fromt he database and show it in the profile page rather the current static plan

cool , this makes sense , good job !

**Pull request merged**
