### PR TITLE
Sharing Feature Added 

### PR DESCRIPTION
**Pull request by aditiverma-21**
Sharing feature added with reforked branch @hiteashgupta1 please check.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
screenshots of the feature ?

**Comment by aditiverma-21** [comment]
image
Added the share button and also
image
when clicked on share these options show.

**Comment by ANSHIKA-26** [comment]
could you make the UI better ? one clicking on share , the screen that opens is pretty basic , it would look better in form of a small drop down rather than this section occupying half of the page

**Comment by aditiverma-21** [comment]
Yes sure let me make changes.

**Comment by aditiverma-21** [comment]
image
Is this okay ??

**Comment by aditiverma-21** [comment]
@hiteashgupta1 please add labels and level to this PR.

**Comment by aditiverma-21** [comment]
@hiteashgupta1 Thank you

**Review by hiteashgupta1 — COMMENTED** [review]
Okay

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by ANSHIKA-26** [comment]
can you show a video of the whole page ? i cant figure out the size by a cropped image

**Comment by aditiverma-21** [comment]
Yes sure I will the demo video

**Comment by aditiverma-21** [comment]
@ANSHIKA-26 please check the ss
image

**Comment by aditiverma-21** [comment]
https://github.com/user-attachments/assets/675c1c7d-278f-4ef7-ab50-d8a389aa5697

and a video for the same.

**Pull request merged**
