### PR TITLE
Seo improvement ans accessibility fixes

### PR DESCRIPTION
**Pull request by SumaLatha2023**
### SEO and Accessibility Enhancements 

I've made key improvements to enhance both **SEO** and **accessibility** on the website:

- **SEO**: Optimized alt attributes, and internal links for better search engine visibility.
- **Accessibility**: Added `aria-label` to buttons, input, and navigation for improved screen reader compatibility and enhanced keyboard navigation.

These updates will boost both user experience and search performance, making the site more inclusive and discoverable. 

Looking forward to your feedback!

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by SumaLatha2023** [comment]
#1129

**Comment by hiteashgupta1** [comment]
@SumaLatha2023 wrong issue number 
Kindly mention correct issue number 
Haven't you raised issue

**Comment by hiteashgupta1** [comment]
@SumaLatha2023 You have to Raise issue first

**Pull request merged**
