### PR TITLE
Create 404.html

### PR DESCRIPTION
**Pull request by vishantrathi**
### Pull Request Checklist

ISSUE NO #1768

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .
image

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by vishantrathi** [comment]
ISSUE NO #1768

**Comment by ANSHIKA-26** [comment]
this is PR number , you never raised an issue and we already have 404 not found page for the html website , we do not need it for the react frontend !
https://github.com/ANSHIKA-26/WordWise/blob/main/404.html

**Comment by ANSHIKA-26** [comment]
kindly raise issue , wait for it to be assigned and only then make a PR !

**Pull request closed without merging**
