### PR TITLE
issue #414 Enhanced Signup Functionality with Validation and Password Visibility Toggle

### PR DESCRIPTION
**Pull request by meghanakn473**
This pull request enhances the signup functionality by adding validation for email format and password strength, ensuring users create secure accounts. It also introduces a password visibility toggle feature for improved user experience.

Screenshot (144)

Screenshot (145)

### CODE REVIEW

**Comment by meghanakn473** [comment]
@ANSHIKA-26 please assign me the level 3 label

**Comment by ANSHIKA-26** [comment]
follow pr checklist ! what is your  issue number ?

**Comment by ANSHIKA-26** [comment]
fixes #414

**Comment by meghanakn473** [comment]
> fixes #414

yess please assign the level 3 label and merge

**Comment by ANSHIKA-26** [comment]
> > fixes #414
> 
> yess please assign the level 3 label and merge

1. the label was level 2 in the issue . we are not supposed to change it now 
2. i need to review your code before merging

**Comment by Shariq2003** [comment]
@meghanakn473 sorry for addresing the issues, but your fixes still not working

**Comment by meghanakn473** [comment]
> > > fixes #414
> > 
> > 
> > yess please assign the level 3 label and merge
> 
> 1. the label was level 2 in the issue . we are not supposed to change it now
> 2. i need to review your code before merging

hey @ANSHIKA-26 my points after merging this are not added in leaderboard can u please check and assign me level 2 label

**Pull request merged**
