### PR TITLE
Added PR Validator Github Action

### LINKED ISSUE #1091: Adding github action workflow for PR validation
**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include Fixes #NEW

@ANSHIKA-26 
Pls assign me this issue and give me level3,gssoc-extd,hacktoberfest

### PR DESCRIPTION
**Pull request by ygowthamr**
**What i have done :**
 - Solved Adding github action workflow for PR validation
Fixes #1091

@ANSHIKA-26 
Pls add me labels like gssoc-extd,level3,hacktoberfest-accepted.

### CODE REVIEW

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Pls accept my PR

**Comment by ANSHIKA-26** [comment]
also add an automated check , if there is any merge conflict then it asks them to resolve conflict !

**Comment by ANSHIKA-26** [comment]
you only added 2 checks , i asked for more like merge conflict and one for checking if template is being followed or not

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
I will make it as another task 
Please accept this pr

**Comment by ygowthamr** [comment]
@ANSHIKA-26 

Accept my pr

**Comment by ANSHIKA-26** [comment]
> @ANSHIKA-26
> 
> Accept my pr

why exactly is that ?

**Comment by ANSHIKA-26** [comment]
> @ANSHIKA-26 I will make it as another task Please accept this pr

why ? you are doing work on the same file , why new PR ? how does that help ?

**Comment by ygowthamr** [comment]
@ANSHIKA-26 


But when there is conflict in merging GitHub it self tells contributor that there is a conflict in merging the file

**Comment by ygowthamr** [comment]
@ANSHIKA-26 
Can you respond

**Comment by ANSHIKA-26** [comment]
lets see if this workflow works , then decide whether to add more or not

**Comment by sanjay-kv** [comment]
Workflows cant be given level 3, kindly reduce to level1 as per guidelines. 
also provide a write access to the repo so we can help you reduce spams and labels. 

the label you followed is incorrect as well. it should be `level3`

**Comment by aditya-bhaumik** [comment]
@ANSHIKA-26 please reduced the level for this pr as we had mentioned in the guidelines that workflow updates need to be given only level 1

**Pull request merged**
