### PR TITLE
Created navbar sticky and set correct redirection links of navbar

### LINKED ISSUE #1120: Navbar Not Sticky on Scroll
**Describe the bug**
The navigation bar is not sticking to the top of the page when scrolling, even though it is expected to remain fixed in view as the user scrolls down the page.

**To Reproduce**
1. Steps to reproduce the behavior:
2. Go to the homepage (or the relevant page where the navbar is implemented).
3. Scroll down the page.
4. Observe that the navbar does not remain visible at the top of the page.
5. See error: the navbar disappears as you scroll.

**Expected behavior**
The navigation bar should remain fixed at the top of the page while scrolling, maintaining visibility at all times for easier navigation.

**Screenshots**

**Additional context**
The navbar is intended to have a sticky or fixed position but appears to be incorrectly implemented or missing necessary CSS properties for it to function as expected. The issue may be related to CSS class definitions or conflicting styles elsewhere in the codebase.

### PR DESCRIPTION
**Pull request by shivam8112005**
### Pull Request Checklist
Fixes #1120 
screenshot:
Screenshot 2024-10-18 152847

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by shivam8112005** [comment]
hey @ANSHIKA-26  check this out is there any problem?

**Comment by ANSHIKA-26** [comment]
can you record a video of the changes done ?

**Comment by shivam8112005** [comment]
https://github.com/user-attachments/assets/b3564f59-cd4f-42ca-8909-cb6f0d8db1d2

github not supporting large videos

**Comment by shivam8112005** [comment]
I have also corrected redirection links in navbar

**Pull request merged**
