### PR TITLE
updated footer section

### PR DESCRIPTION
**Pull request by Antima2004**
updated again footer in the index.html
Before:
WhatsApp Image 2024-10-05 at 10 20 36 PM

After:
WhatsApp Image 2024-10-05 at 10 19 52 PM
please merge #82

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
hey , can you share a video showing each page of the website having this footer

**Comment by Antima2004** [comment]
Hey,
Here is a video that show each page of the website having this footer

https://github.com/user-attachments/assets/6789318f-4ea6-437c-a5a8-13fe73b4c2ba

**Comment by hiteashgupta1** [comment]
@Antima2004 not showing footer in the page
Refork and align footer at each page

**Comment by Antima2004** [comment]
@ANSHIKA-26  please merge this pr

**Pull request closed without merging**
