### PR TITLE
Enhanced the FAQ section in dark mode

### LINKED ISSUE #495: Improving FAQ section in Dark mode
As shown in the image when the questions are expanded in dark mode the users will be unable to read the answers written as the font color is very light. Also the background color of the FAQ section doesn't really go with the website and isn't soothing to the eyes. I can help in creating a more attractive and easy to read FAQ section.

image

### PR DESCRIPTION
**Pull request by master-ginger**
Fixes #495 

https://github.com/user-attachments/assets/639b6b61-2732-4b7e-9628-13b9ff327feb

I have improvised the design and also made the content readable in dark mode

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
can you also decrease font size of FAQ ?

**Comment by master-ginger** [comment]
Sure. But do you mean the title only or the entire section?

**Comment by ANSHIKA-26** [comment]
entire section , and do record another video/ image

**Comment by master-ginger** [comment]
https://github.com/user-attachments/assets/ec7c27f8-5fcf-4de5-b3a4-f2e98ca94c1d

Reduced the font size for the entire FAQ section.

**Comment by ANSHIKA-26** [comment]
sync fork please

**Pull request merged**
