### PR TITLE
Complete Project Restructure

### PR DESCRIPTION
**Pull request by NK-Works**
### Pull Request Checklist

image
here's the screenshot of the project restructure... 
Now couple of things to keep in mind...
if you are making this the main dir then you need to make sure that all the other contributors make a  new fork of the project...
And as u know u also need to upgarde the fork manually maybe...
Finally make it a level3 solution..
I ended up changing a lot (i mean a lot of things) in the project to make it professional. :)
Thanks:)

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by NK-Works** [comment]
@ANSHIKA-26 ignore the conflict you will need to delete the extra files and code any way due to the restructure.

**Comment by NK-Works** [comment]
ProTip: visit my fork to understand the complete restructure and maybe run that fork once locally to see how everything works... **Branch: restructure**
And then upgrade the main project

**Comment by ANSHIKA-26** [comment]
> @ANSHIKA-26 ignore the conflict you will need to delete the extra files and code any way due to the restructure.

i cant merge with conflicts

**Comment by NK-Works** [comment]
@ANSHIKA-26 dunno how can i resolve these conflicts directly... 
Maybe you can first delete the files not reqd (shifted) and then merge...
or create a new branch

**Comment by ANSHIKA-26** [comment]
@hiteashgupta1 @ushmita4 kindly help

**Comment by hiteashgupta1** [comment]
@NK-Works Do you want us to add frontend and backend files in separate folder on GitHub

**Comment by ANSHIKA-26** [comment]
Thank you so much for your hard work on restructuring the project files! I really appreciate the effort you put in. Unfortunately, there are too many merge conflicts, and after discussing it, we realized it would be easier to handle these changes locally.

I apologize for not identifying this issue earlier, which would have saved you the trouble. I will be closing this PR, but please know that your contributions are valued!

**Comment by NK-Works** [comment]
@ANSHIKA-26 I got an interesting idea.. if u wanna hear...
can you just put this code in a branch of the repo somthing like **stable version**
no need to use it for the PRs but you see it will add some points in my profile and wont interfare with the main branch as well so that you can continue with the project as it is and do changes after GSSOC ends.
Just suggesting **No Offense :)**

**Pull request closed without merging**
