### PR TITLE
Redesigned the UI

### PR DESCRIPTION
**Pull request by Dipeshdahiya**
I have redesigned the contact page , took care of the responsiveness , as well as the layout of the form for different screens and also adjusted the social icons

### Pull Request Checklist

- [ done] I have added screenshots and videos to show before and after the working of my code.
- [done ] I have ensured that the screen size is set to 100% while making the video.
- [done] I have synced the latest fork with my local repository and resolved any conflicts.
- [ done] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [done ] I understand that if any the above conditions are not met , my PR will not be MERGED .
Screenshot 2024-10-22 174617

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by Dipeshdahiya** [comment]
Issue number - #1217

**Comment by ANSHIKA-26** [comment]
good job !
but these icons get almost invisible in dark mode , kindly fix this !
image

**Comment by ANSHIKA-26** [comment]
even in light mode the color doesnt align with out theme , could you change that ? anything instead of black works

**Comment by Dipeshdahiya** [comment]
sure ma'am

**Comment by Dipeshdahiya** [comment]
Screenshot 2024-10-23 111145
Screenshot 2024-10-23 111208
looking good from my side , please check it if any another change needed

**Comment by Dipeshdahiya** [comment]
and i want to work on as many issues as possible so if you have any other issue pending regarding designing please allow me to work on under gssoc-ext.

**Comment by hiteashgupta1** [comment]
Add validation to it as it is already there

**Comment by Dipeshdahiya** [comment]
Can you please specify what i have to add exactly on the page?

**Comment by hiteashgupta1** [comment]
Check existing validation on the page add that to it

**Comment by Dipeshdahiya** [comment]
image

validation is working now please check

**Comment by Dipeshdahiya** [comment]
Also please update me regarding the next issue i want to work on regarding the feedback form on the site page.

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by ANSHIKA-26** [comment]
someone else is working on feedback page

**Comment by Dipeshdahiya** [comment]
conflicts resolved

**Comment by ANSHIKA-26** [comment]
more conflicts

**Pull request closed without merging**
