### PR TITLE
Fixing_footer

### LINKED ISSUE #649: BUG: Fixing Footer
**Describe the bug**
At the end of the page, there is one text stating "this script is to display year...."
I can fix it

image

**Expected behavior**
Year and copyright symbol should be added

### PR DESCRIPTION
**Pull request by Abhi9shinde**
image

image

I have successfully fixed the bug in the footer section.
And as you requested I have also removed the text stating "Created by Anshika".
Also did some extra task: As Contact Us page didn't had footer so added it.

### Pull Request Checklist

 issue number is : fixes #649 

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

please give it a level

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by Abhi9shinde** [comment]
@ANSHIKA-26 please review the PR, I have synced my fork.
If there are any mistakes please bear with me this is my first time doing open source so this sync fork and merge conflicts are new to me

**Comment by ANSHIKA-26** [comment]
no problem , just sync fork again

**Comment by Abhi9shinde** [comment]
@ANSHIKA-26 Synced fork, please review

**Pull request merged**
