### PR TITLE
fixes #1380 Update font-awesome version and fix social media icons

### LINKED ISSUE #1380: Non-Visibility of the X logo when switched to dark mode
**Describe the bug**

When switched to dark mode the logo of the X is not visible

**To Reproduce**
1. Go to Footer
2. Click on Dark Mode switch
3. See error

**Expected behavior**

There should be a background of white to show the logo perfectly

**Screenshots**
{6D08D9B8-7715-4DDC-AC41-0A34C7B560CC}

{0EE6E55F-8014-4FF9-92AC-286195A7C200}

**Additional context**

### PR DESCRIPTION
**Pull request by harjasae2001**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

{33A11483-5A12-46B8-A2E6-C737E3C0720B}

{B0380500-93D0-4ED7-A7DF-0B922667059A}

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
footer on rest of the pages -
image
footer on leading blog page-
image


kindly fix

**Comment by hiteashgupta1** [comment]
@harjasae2001 Why have you removed hover on icons

**Comment by hiteashgupta1** [comment]
#1380

**Comment by harjasae2001** [comment]
I was working on this for the past one week and now you have closed this one. At that time it was not visible I fixed that problem them u assigned me to fix another problem then another in that time someone else might have fixed that issue.
So how is it my mistake also my PR gets rejected everytime.

**Comment by hiteashgupta1** [comment]
@harjasae2001 You have to check at the time of making pr. If you have raised issue then you have to make it resolved timely , someone might have improved in his pr without raising a separate issue.

**Pull request closed without merging**
