### PR TITLE
Improvized signup page , added scroll-reveal animation , added a back to top button

### PR DESCRIPTION
**Pull request by aditya07389**
## Before :
There was no scroll reveal feature 
## After Adding scroll reveal it looks like this :

https://github.com/user-attachments/assets/3d1f0891-b04e-4244-b0e4-5cbab3e5ae74

2) Added Back to top button :
before there was no back to top feature

## after adding

https://github.com/user-attachments/assets/faea415e-cc89-46cb-8182-8028b07cb1ec

## 3) Signup:

##before :
image
##After :
https://github.com/user-attachments/assets/2800f9ba-5615-4dad-abca-a7d8a1b3c94c

### CODE REVIEW

**Comment by aditya07389** [comment]
Hope you are satisfied with my work 
 
 # kindly add the labels level 3 , gssoc extd and hacktoberfest

**Comment by ANSHIKA-26** [comment]
fixes #539

**Comment by aditya07389** [comment]
Hey @ANSHIKA-26 what's the issue

**Comment by ANSHIKA-26** [comment]
make the back to top button something simpler , just an arrow facing up is okay ,this looks weird

**Comment by aditya07389** [comment]
Okay I'll change

**Comment by ANSHIKA-26** [comment]
its nice , kindly make a new PR with the said changes , resync your fork

**Pull request closed without merging**
