### PR TITLE
Update index.html for Twitter icon

### PR DESCRIPTION
**Pull request by Antima2004**
I updated the Twitter icon in the footer section

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
screenshots showing before and after changes

**Comment by hiteashgupta1** [comment]
Share the relevant screenshots

**Comment by Antima2004** [comment]
Before:
Screenshot 2024-10-04 10 31 59 PM
After:
WhatsApp Image 2024-10-04 at 10 59 16 PM

**Comment by Antima2004** [comment]
@ANSHIKA-26 
@hiteashgupta1 
please merge it #217

**Comment by Antima2004** [comment]
Hello, @ANSHIKA-26 
Please remove space between level1 as i not get's any points under gssoc leaderboard.

**Pull request merged**
