### PR TITLE
Redesign "Leave Comment" Section on Leading Blog Page

### LINKED ISSUE #749: ✨ Enhancement: Redesign "Leave Comment" Section on Leading Blog Page
### Description:
On the Leading Blog page, the "Leave Comment" section currently takes up too much space, which negatively affects the overall layout and user experience. I propose a minimal UI redesign to make it more compact and space-efficient. I would like to contribute by implementing this improved design.

image

### PR DESCRIPTION
**Pull request by Rahul-AkaVector**
### Description

This PR implements a redesign of the "Leave Comment" section on the Leading Blog page. The previous layout was too spacious, negatively impacting the overall user experience. The new design arranges the elements vertically, making the section more compact and space-efficient. This enhancement aims to improve the UI and make browsing easier without unnecessary scrolling.

Fixes #749

### Type of change

- [x] Enhancement (non-breaking change which adds functionality or improves existing functionality)

### Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added screenshots or videos that demonstrate the before and after state of my changes.
- [x] I have mentioned the issue number in the format `fixes #749`.

### Screenshots

**Before**  
The "Leave Comment" section was arranged horizontally, taking up too much space.
{2C46AD23-F725-434E-9FD4-BE3ED87BC7E5}

**After**  
The "Leave Comment" section is now vertically arranged, providing a more compact design that enhances the overall layout and improves user experience.

{B2D7530E-FD82-4398-858D-546153A8052C}

### Issue Link

Fixes #749

### Additional Notes

This redesign is intended to create a cleaner interface and improve usability on the Leading Blog page by reducing unnecessary scrolling.

---

### Pull Request Checklist

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by Rahul-AkaVector** [comment]
@ANSHIKA-26 kindly look into this PR and let me know if any chnages are required

**Comment by ANSHIKA-26** [comment]
image
seems out of place , either remove it or align it somehow

**Comment by ANSHIKA-26** [comment]
add a little shadow effect on the box , very light

**Comment by Rahul-AkaVector** [comment]
Sure!

**Comment by Rahul-AkaVector** [comment]
> add a little shadow effect on the box , very light

can u specify which box exactly ??

{00FB892B-A733-48F0-B728-2628FD395A5B}


this box already has shadow effect , should i increase it ?

or add shadow effect at input fields ?

{5912CC8F-A454-4B80-9B29-E85EBEC69087}

**Comment by Rahul-AkaVector** [comment]
### Pull Request Title: Enhance Comment Form Layout and Style

### Description:
This pull request introduces improvements to the comment form layout and styles to enhance user experience and maintain the UI's integrity.

### Changes Made:
- **Adjusted Layout**: 
  - The "Website (Optional)" input field has been positioned to the right side of the message textarea, allowing for a more organized layout that doesn't interfere with the overall UI.
- **Shadow Effects**:
  - Added a subtle purple shadow effect to the input fields and textarea for better visual distinction.
  - Applied a blue shadow effect to the submit button to enhance its visibility.

### Screenshot:
Comment Form Layout

### Request for Review:
@ANSHIKA-26 , could you please take a moment to review the changes in this pull request? Your feedback would be greatly appreciated!

**Comment by ANSHIKA-26** [comment]
great job , sync fork

**Comment by Rahul-AkaVector** [comment]
Done!

**Pull request merged**
