### PR TITLE
[FIX] About page delete & all nav bar changed v1

### LINKED ISSUE #1130: [BUG] Footer Link Icons Jittering on About Page
**Describe the bug**
- Footer Link Icons Jittering refers to icons shaking or flickering on hover or load. Common causes include:

- Hover Effects & Transitions: Abrupt changes in padding, margin, or size during hover can cause icons to shift or "jump."
- Icon Size Changes: Scaling or resizing icons on hover without smooth transitions may create a jittery effect.
- Font Rendering Issues: Icons from libraries like Font Awesome may jitter due to inconsistent font rendering or alignment issues.

**To Reproduce**
1. Go to https://anshika-26.github.io/WordWise/about.html
2. Scroll down to '....'
3. See error

**Expected behavior**
Icons should not be jittery, but a hover effect should be present.

**Screenshots**

https://github.com/user-attachments/assets/e93de48e-8e1a-4ff1-8b2c-4cb82228c939

**Additional context**
Add any other context about the problem here.### Please add hactoberfest and GSSoC24 tag. You can assign me for this issue.

### PR DESCRIPTION
**Pull request by 4F24L**
- Fixes #1130 

image

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
more conflicts

**Comment by 4F24L** [comment]
@ANSHIKA-26 Please merge this PR before any PR. So, the About page can be deleted.
Otherwise, that page will be coming back again and again.

**Comment by ANSHIKA-26** [comment]
yess , was on it , but the UI of navbar is twice in your code somehow , kindly fix it

**Comment by ANSHIKA-26** [comment]
your PR will be merges ASAP coz of deleting page !

**Comment by 4F24L** [comment]
> yess , was on it , but the UI of navbar is twice in your code somehow , kindly fix it

On which page ?

**Comment by ANSHIKA-26** [comment]
image

**Comment by 4F24L** [comment]
Okay, fixing it ASAP!

**Comment by ANSHIKA-26** [comment]
go through the whole website once ,
1. make sure no unnecessary pages are linked 
2. things are working ok in light/dark more 
 then inform me asap , will merge before others

**Comment by 4F24L** [comment]
Okay, surfing the website for any error.

**Comment by 4F24L** [comment]
Now check !!

**Comment by 4F24L** [comment]
Somehow, something error is occuring.

I am opening  a new PR with all checks.

**Comment by 4F24L** [comment]
Please review the new working PR  @ANSHIKA-26 
- #1207

**Pull request closed without merging**
