### PR TITLE
Add PWA (Progressive Web App) done ! #1729

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add/Enable PWA (Progressive Web App) done ! #1729 
🌟Benefits of PWAs: Improved Performance and Speed, Offline Availability, Enhanced User Engagement, Responsive and Adaptive Design, Low Storage Requirements... & more..

Screenshot 2024-11-07 162853

https://github.com/user-attachments/assets/74d76bb4-e3ad-4d27-8cb0-70456ccc3616

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 done #1729

Please merge my PR with Level 3 and gssoc-ext label

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 conflicts solve

**Comment by ANSHIKA-26** [comment]
image
check the deployment , what exactly is this ?

**Comment by Subhajit-2023-44** [comment]
> image check the deployment , what exactly is this ?

Okay I will give new PR

**Comment by Subhajit-2023-44** [comment]
@ANSHIKA-26 please check and merge my PR #1749

**Pull request closed without merging**
