### PR TITLE
fixed mini chatbot issue

### PR DESCRIPTION
**Pull request by rutikakengal**
#215 issue add mini chatbot fixed 
Add gssoc-ext, hactoberfast accepted and level 3 to this Pr , As you want i created this chatbot which shows in one side of the website .  Done 👍@ANSHIKA-26

Screenrecording

https://github.com/user-attachments/assets/c5268a3a-822d-4ac3-8c14-319b86be58fe

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
resolve conflicts

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by hiteashgupta1** [comment]
@rutikakengal The website is not loading kindly check the files

**Review by hiteashgupta1 — CHANGES_REQUESTED** [review]
Fix properly

**Comment by NK-Works** [comment]
@ANSHIKA-26 I can work on it if you want

**Comment by ANSHIKA-26** [comment]
@rutikakengal if you do not respond , the issue will be given to @NK-Works , and since @NK-Works will be making the PR , the points will go to her , kindly update

**Comment by rutikakengal** [comment]
I am working on it @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
fix merge conflicts , you might need to resync and refork , and make another PR

**Comment by rutikakengal** [comment]
Ok @ANSHIKA-26

**Pull request closed without merging**
