### PR TITLE
Done with changes #1646 and #1644

### PR DESCRIPTION
**Pull request by Ashmitha2606**
### Pull Request Checklist
issues: #1646 and #1644 
profile changes done with leading blog page change
Screenshot 2024-11-03 173424

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .

Screenshot 2024-11-04 161157
Screenshot 2024-11-04 161146

### CODE REVIEW

**Comment by Ashmitha2606** [comment]
@ANSHIKA-26 check

**Comment by ANSHIKA-26** [comment]
@Ashmitha2606 
on clicking profile our current login looks like -
image

whereas in your preview it has removed the close and dont have an account , signup here button , 
same issue with signup page
kindly preview your changes and match with current website , make sure that while adding things you are not removing the already existing functionalities of the website !

**Comment by Ashmitha2606** [comment]
@ANSHIKA-26 ...Done with changes!!

**Comment by Ashmitha2606** [comment]
> @Ashmitha2606 on clicking profile our current login looks like - image
> 
> whereas in your preview it has removed the close and dont have an account , signup here button , same issue with signup page kindly preview your changes and match with current website , make sure that while adding things you are not removing the already existing functionalities of the website !

ya since i have old fork of ur website the form and sign page at that time was without close and signup features...So now i have matched that to ur current website

**Comment by ANSHIKA-26** [comment]
sync fork again , the profile section has been removed

**Comment by Ashmitha2606** [comment]
> sync fork again , the profile section has been removed

@ANSHIKA-26 check it i have sync again

**Comment by Ashmitha2606** [comment]
@ANSHIKA-26 view the latest preview

**Comment by Ashmitha2606** [comment]
@ANSHIKA-26 hey please add gssoc tags to that points will be added

**Comment by ANSHIKA-26** [comment]
thats the problem , we removed the profile section ! someone is working on it !

**Comment by Ashmitha2606** [comment]
Ok then should I remove profile section from all pages profile?

**Pull request closed without merging**
