### PR TITLE
Improve the navbar

### PR DESCRIPTION
**Pull request by VidhanThakur09**
All the issue related navbar and Misleading Text "TranslationTool" Above Navbar has been fixed .

Fixed Issue #1168 

*Improvements:*

1. *Optimized CSS of navbar:* Enhanced the navbar on every pages to improve user experience.

2. *Remove all the Misleading texts:* removing misleading texts from  Leading blog , contact us and give feedback pages.

## How Has This Been Tested? 

The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.

## Screenshots 📷

**Before changes** 

Screenshot 2024-10-19 003415

**After Improvement**

https://github.com/user-attachments/assets/688ee8e2-fc1d-450f-aaa7-9e5e223aa65d

### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
make navbar sticky

**Comment by VidhanThakur09** [comment]
ok mam

**Comment by ANSHIKA-26** [comment]
what you have done :
image

what i want 
image

**Comment by VidhanThakur09** [comment]
ok mam let me fix this

**Comment by ANSHIKA-26** [comment]
image
fix this

**Comment by ANSHIKA-26** [comment]
image
on clicking on the logo , we should redirect to our homepage

**Comment by VidhanThakur09** [comment]
ok mam 

Screenshot 2024-10-19 234251
is this good mam

**Comment by ANSHIKA-26** [comment]
make the headings a little bold , and a little larger

**Comment by VidhanThakur09** [comment]
Screenshot 2024-10-19 234802
how about now mam

**Comment by ANSHIKA-26** [comment]
nice

**Comment by VidhanThakur09** [comment]
ok mam now i will continue working on toggle option , redirecting logo and sticky nav.

**Comment by ANSHIKA-26** [comment]
keep syncing fork , do this asap , i wont merge prs related to navbar till you are doing this

**Comment by VidhanThakur09** [comment]
ok mam
is it possible if i raise the pr late night

**Comment by VidhanThakur09** [comment]
Screenshot 2024-10-20 003017

- navbar is converted into a sticky
- toggle option of dark mode and light mode have been fixed
- font size of the nav links has been increasing and bold
- logo is formated to redirect to home page

**Comment by ANSHIKA-26** [comment]
can you record a video of the same ? the preview deployed isnt showing changes

**Comment by VidhanThakur09** [comment]
Merge conflict fixed
issue fixed #1168

https://github.com/user-attachments/assets/3f71cff0-0b42-47a2-b20f-0e92bb35fa75


https://github.com/user-attachments/assets/6fda3e8b-cfce-45b1-9c1e-8445295bc9ae

**Comment by ANSHIKA-26** [comment]
can you improve the navbar elements to look well aligned , right now there is a lot of empty space from the right

**Pull request merged**
