### PR TITLE
Improved text color and added shadows.

### LINKED ISSUE #1099: Text on Categories section in Leading Blog is not properly visible
**Describe the bug**
Text on Categories section in Leading Blog is not properly visible can change the colors to make it more visually appealing.

**To Reproduce**
1. Go to 'WordWise'
2. Click on 'Leading Blog'
3. Scroll down to 'Categories'

**Expected behavior**
When we hover on categories it is visible properly but when not hovering it is not visible properly

**Screenshots**

Screenshot 2024-10-17 142013

**Additional context**

### PR DESCRIPTION
**Pull request by AnujSisodiya**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is :
-  fixes #1099
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

Before-
Screenshot 2024-10-17 142013

After-

https://github.com/user-attachments/assets/573065ca-936b-42f0-a263-ead6f6920aac

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
just make it white even without the hover , this pink shade isnt visible either

**Comment by AnujSisodiya** [comment]
https://github.com/user-attachments/assets/d2f92863-4c3a-412a-8ebb-82cd01d0cd0f

Is this good?

**Comment by ANSHIKA-26** [comment]
idk why but its showing like you messed up the light / dark mode button a bit ? could you share a video ? also check the vercel deployment

**Comment by AnujSisodiya** [comment]
Yes  light / dark mode is messed up but I haven't changed any code in index.html.  light / dark mode button in other pages  is at correct pages.

**Comment by ANSHIKA-26** [comment]
might be due to old fork ,  you should refork and make a NEW pr , will help !

**Comment by AnujSisodiya** [comment]
okay!!!

**Pull request closed without merging**
