### PR TITLE
Fixes #39 improved folder structure

### LINKED ISSUE #39: Improving the folder structure for open source contributions
Hey  @ANSHIKA-26  I want to work on this issue
Please assign this under gssoc-ext  level 2

### PR DESCRIPTION
**Pull request by rishyym0927**
### Pull Request Checklist

I have improved the folder structure so that it become easy to work on it. Fixes #39 

- [x] I have added screenshots and videos to show the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
doing this will affect all the paths in the code as well , have you ensured that all paths are changed accordingly and are working ?

**Comment by rishyym0927** [comment]
Yes but I will raise other issue else, you mark it as a level 3 cause its a huge work

**Comment by hiteashgupta1** [comment]
Share relevant screenshots of what you have done

**Comment by ANSHIKA-26** [comment]
hello , kindly sync your fork and make a NEW pr if required

**Comment by rishyym0927** [comment]
@abhishekraoas   Please add label gssoc-ext Level3 . Else it wont be counted. 
Please check the spelling and correct it

**Pull request closed without merging**
