### PR TITLE
done with changes #1646 , #1644

### PR DESCRIPTION
**Pull request by Ashmitha2606**
issue: #1644 and #1646
Description: changed profile icon for all pages and change the whole ui of blog page added hovering to buttons created cards to the elements changed  completely a new look
before the change
Screenshot 2024-11-03 172718
Screenshot 2024-11-03 172730
Screenshot 2024-11-03 173416
Screenshot 2024-11-03 173424
after the change
Screenshot 2024-11-04 161113
Screenshot 2024-11-04 161126
Screenshot 2024-11-04 161137
Screenshot 2024-11-04 161146
Screenshot 2024-11-04 161157
Screenshot 2024-11-04 161209
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by Ashmitha2606** [comment]
@ANSHIKA-26  check it

**Comment by hiteashgupta1** [comment]
Check the font colour in light mode improve it

**Comment by Ashmitha2606** [comment]
@hiteashgupta1 is it for leading blog page

**Comment by hiteashgupta1** [comment]
Yes

**Comment by ANSHIKA-26** [comment]
image
why does the leading blog page has this ?

**Comment by ANSHIKA-26** [comment]
@Ashmitha2606 undo all the changes you did to leading blog page

**Comment by Ashmitha2606** [comment]
@ANSHIKA-26 done with the changes

**Comment by ANSHIKA-26** [comment]
this is how blog.html looks like in light mode 
image
the buttons are barely visible

**Comment by Ashmitha2606** [comment]
Will make the changes

**Comment by ANSHIKA-26** [comment]
i liked the old profile icon better , i told you to make the old icon on all pages , you implemented new icon on all , kindly fix that as well

**Comment by Ashmitha2606** [comment]
Sorry for the misunderstanding I will make the changes

**Comment by Ashmitha2606** [comment]
Im closing this request and creating a new one @hiteashgupta1 for this thanks

**Pull request closed without merging**
