### PR TITLE
Enhanced the navbar's UI #517

### PR DESCRIPTION
**Pull request by Deepak0yadav**
1.  **Resolved ** #517 issue 
2.  Changed the **Login Icon ** 
3.   Added **Spacing** between navbar elements
4.   Removed the **Hover**effect for better UI

Screenshot 2024-10-08 013405

### CODE REVIEW

**Comment by Deepak0yadav** [comment]
Please preview the fixes and merge it

**Comment by Deepak0yadav** [comment]
Please preview the fixes and merge it

**Comment by Deepak0yadav** [comment]
Please preview the fixes and merge it

**Comment by ANSHIKA-26** [comment]
fix merge conflicts

**Comment by ANSHIKA-26** [comment]
navbar is completely inconsistent across pages , kindly follow PR guideline s, fix it across all pages , record a video

**Comment by ANSHIKA-26** [comment]
navbar is messing up on leading blog page , and also once we login/ sigup

**Comment by Deepak0yadav** [comment]
@ANSHIKA-26  ok I will try to enhance all of them

**Comment by Deepak0yadav** [comment]
@ANSHIKA-26 , I have made the necessary changes to the Navbar for all the landing pages.


https://github.com/user-attachments/assets/e10581d1-e4d1-4379-8148-40133ece3e59

**Comment by ANSHIKA-26** [comment]
resolve merge conflicts

**Comment by ANSHIKA-26** [comment]
change the hover effect to a decent underline effect , not this oval hover

**Comment by Deepak0yadav** [comment]
> resolve merge conflicts

How can I resolve it

**Comment by Deepak0yadav** [comment]
> you had a nice underline effect earlier , i wanted that on all pages , why would you change it to an oval hover , it looks too big

Can I enhance that hover effect instead of that underline effect .I will try to make it more user friendly

**Comment by Deepak0yadav** [comment]
can u please assist me how can i resolve the conflicts.

**Comment by ANSHIKA-26** [comment]
image

this is what i want for hover , you might find the code in some old PR as well

**Comment by ANSHIKA-26** [comment]
> @ANSHIKA-26 ,can u please assist me how can i resolve the conflicts.

im gonna close this PR , please, resync and then make a new PR , keep your code somewhere since you might loose it if you refork as well :)

**Comment by ANSHIKA-26** [comment]
@Deepak0yadav due to your lack of response , and not completing the PR on time , this issue has been assigned to others , kindly do not work on it anymore

**Pull request closed without merging**
