### PR TITLE
change in logo and nav bar

### PR DESCRIPTION
**Pull request by tabish-000**
Screenshot 2024-10-16 162318
### Pull Request Checklist

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by tabish-000** [comment]
I changed in your travel websites logo and also small change in navbar. 
Thanks

**Comment by hiteashgupta1** [comment]
Kindly follow pr checklist

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
1. kindly follow PR checklist 
2.the logo is very basic, we dont need it

**Pull request closed without merging**
