### PR TITLE
Feat: RevampFeedForm

### LINKED ISSUE #927: [FEAT] : Wanna ADD Modified UI of Feedback Form
Is your feature request related to a problem? Please describe.
@ANSHIKA-26 , I would like to bring to your attention a small issue I encountered with the navigation functionality on the website. Currently, both the "Contact Us" and "Give Feedback" links in the navigation bar redirect to the same page [https://word-wise-4d50.onrender.com/contact_us.html].

Describe the solution you'd like
I just want to change the UI of form for better user experience and clarity, it would be ideal if each link led to its respective dedicated page, ensuring the proper distinction between contacting support and providing feedback.

Describe alternatives you've considered
Since both the "Contact Us" and "Give Feedback" options currently lead to the same page, it may be more efficient and user-friendly to keep only one of these options in the navigation bar.

Additional context
Screenshot 2024-10-14 002327

### PR DESCRIPTION
**Pull request by shivisingh25**
Pull Request Checklist
fixes #927 
Screenshot 2024-10-14 002327
Screenshot 2024-10-14 234751

- [x] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by shivisingh25** [comment]
@ANSHIKA-26 I wanted to let you know that I have created a pull request (PR) for your review. When you have a moment, could you please take a look at it? I would greatly appreciate your feedback and approval for merging it.

**Comment by hiteashgupta1** [comment]
Kindly follow pr checklist 
And mention issue number

**Comment by shivisingh25** [comment]
@hiteashgupta1 I've completed the task, but I inadvertently missed mentioning the issue number. My apologies for the oversight.

**Comment by hiteashgupta1** [comment]
@shivisingh25 It is not submitting it is asking for filling out all fields 
Kindly check 
Screenshot_2024_1015_094746

**Comment by shivisingh25** [comment]
@hiteashgupta1 okay

**Comment by shivisingh25** [comment]
https://github.com/user-attachments/assets/01dba099-67de-4c99-92ad-6e8d2353a4b9

@hiteashgupta1,After your review, I tested it on my PC, and it's working correctly.

**Pull request merged**
