### PR TITLE
Added login/signup buttons working

### PR DESCRIPTION
**Pull request by Priyanshi231**
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

image

**I have made the login/signup buttons working**

image

image

Solved the issue #150

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Why you have closed

**Comment by Priyanshi231** [comment]
I have forgot to sync the code and I made changes in the old code. So, now I am adding login/signup in updated code then I will make other pull request.

**Comment by hiteashgupta1** [comment]
Okay

**Comment by hiteashgupta1** [comment]
Yea you have to make sure changes to be made in recent latest repo

**Pull request closed without merging**
