### PR TITLE
Main

### PR DESCRIPTION
**Pull request by snehas-05**
Hello! 
I have done my best to provide you with the code necessary for the implementation of Infographics feature.
For better understanding of the code, I have made a separate folder named as infographics in which all my code files are placed.

Instructions to Run the Code-
1. Install Required Packages: Ensure you have Python and pip installed, then run the command-
pip install -r requirements.txt

2. Initialize the Database: Before running the application, initialize the database by executing the command-
python app.py

3. Run the Application: Start the Flask application with command-
flask run

4. Access the Application: Open your web browser and go to http://127.0.0.1:5000 to see the WordWise website with the new infographics feature.

I know you are already familiar with these instructions, but I provided them to ensure smooth working of the code and to help any team members who might need additional guidance. 

I request you to kindly merge it. I will be grateful to you.

Thank you for reviewing my pull request!

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
proof of work ?

**Comment by ANSHIKA-26** [comment]
i cannot test this yet :/
also i actually asked you to wait for the backend to be made , before exploring how to do this , we wont be able to integrate it till the backend has been made

**Comment by snehas-05** [comment]
ok so what now? My code will not be considered?

**Comment by ANSHIKA-26** [comment]
it will be considered , its great that you have done work before time, you might need to adjust it a little in order to link it to the backend system (once made) ,
the issue is yours , you will get the points you deserve for sure , do not worry about that !

**Comment by ANSHIKA-26** [comment]
just wait for when the backend is made , you can do the needful changes and then make another pr !

**Comment by snehas-05** [comment]
Okayy I will wait. Will you notify me once the backend is made?

**Comment by ANSHIKA-26** [comment]
yep

**Pull request closed without merging**
