### PR TITLE
Addition of Email Validation, Toast Alert PopUp, Newsletter Endpoint and Newsletter Service | Issue #289

### PR DESCRIPTION
**Pull request by Shariq2003**
1. I have added Email Validation by  regex addition to ensure that the user inputs a valid email address before subscribing.
2. Additon of  toast-style popup notification to provide immediate feedback to the user. It shows a success message when the subscription is successful and an error message in case of failure or invalid email input (Initially Error as the Provider Email and Password should enter by the Admin).

Issue #289 Completed

https://github.com/user-attachments/assets/d42fa79e-718d-4596-8a13-09767b76c0db

### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by NEGRAH-S** [comment]
@MastanSayyad , No authenticating app added it's just regex format. It should be a level 2 PR

**Comment by Shariq2003** [comment]
> @MastanSayyad , No authenticating app added it's just regex format. It should be a level 2 PR

Sir could you please read the changes that I mentioned above,

**Review by MastanSayyad — COMMENTED** [review]
It's fine, comsidering the features that have been implemented!

**Comment by Shariq2003** [comment]
> It's fine, comsidering the features that have been implemented!

Thanks, @MastanSayyad sir,

I appreciate you code review.

**Pull request merged**
