### PR TITLE
Fixed Issues In start_writing.css

### PR DESCRIPTION
**Pull request by rimmon1234**
1.Fixed invalid placeholder content for the textarea.
2.Added focus styles for form elements for better accessibility.
3.Smoothed transitions for the background and button hover effects.
4.Improved popup centering and ARIA role for accessibility.
5.Enhanced dark mode readability with better color contrast.
6.Added animations for the suggestions container (fade-in).
7.Optimized footer layout with gap for better spacing and responsiveness.
Untitled design (1)

### Pull Request Checklist

- [*] I have added screenshots and videos to show before and after the working of my code.
- [*] I have ensured that the screen size is set to 100% while making the video.
- [*] I have synced the latest fork with my local repository and resolved any conflicts.
- [*] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [*] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number

**Comment by ANSHIKA-26** [comment]
could you also fix the issue of this page not scrolling ?

**Comment by ANSHIKA-26** [comment]
in this PR only , will increase to level2 if you can fix this

**Comment by rimmon1234** [comment]
Issue no #1328

**Comment by rimmon1234** [comment]
ok i will check

**Comment by rimmon1234** [comment]
Sorry I Cannot Fix The Scrolling Issue As The Code Is Very Congested And I am still a Beginner So Please Consider

**Pull request merged**
