### PR TITLE
detailed readme.md file

### PR DESCRIPTION
**Pull request by gayu999Code**
# Pull Request Format

## Type of PR
- **Add X in the box to specify the improvement type.**
- [x] Bug fix
- [x] documentation

## Description
This pull request aims to so here I had added detailed readme.md page , which consists information about the project and aslo the vedio of that  

## Screenshots / Videos (if applicable)
**Before:**
image

**After:**
I had added the detailed readme.md
image

## Checklist
- **Add X in the box to specify.**
- [x] I have performed a self-review of my document.
- [x] I have tested the changes thoroughly before submitting this pull request.

Thank you for reviewing my pull request!

### CODE REVIEW

**Review by ANSHIKA-26 — CHANGES_REQUESTED** [review]
hey , could you remove the screenshots portion from the readme ?

**Comment by gayu999Code** [comment]
Yeah, I can do that.

**Comment by gayu999Code** [comment]
@ANSHIKA-26 removed the session of screenshots . Please review the document

**Comment by ANSHIKA-26** [comment]
hey , i have merged another readme , since I found it better, if you wish to make any changes to it , kindly sync fork and make another PR , thank you !

**Pull request closed without merging**
