### PR TITLE
improve colours combination,overlapping of text and hover effect css in footer section issue #1259

### PR DESCRIPTION
**Pull request by rahulbamnuya**
### Pull Request Checklist
Issue : #1259 
Before : 

https://github.com/user-attachments/assets/7c887496-0120-4c9e-ace5-a3b834be43df

After : 

https://github.com/user-attachments/assets/ab12a7fe-1ad3-4d5c-b957-7a274e78e744

https://github.com/user-attachments/assets/397bd09c-926f-4d8c-8414-72594e3b48ea

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
twitter icon not visible in dark mode

**Comment by ANSHIKA-26** [comment]
add a line to separate the footer section

**Comment by rahulbamnuya** [comment]
@ANSHIKA-26 can you review please 
Screenshot (283)
Screenshot (284)

**Comment by ANSHIKA-26** [comment]
resolve conflicts

**Comment by rahulbamnuya** [comment]
@ANSHIKA-26 I will resolve it

**Comment by hiteashgupta1** [comment]
You have added copyright line 2times change it

**Review by hiteashgupta1 — CHANGES_REQUESTED** [review]
Copyright line

**Review by hiteashgupta1 — CHANGES_REQUESTED** [review]

**Review by rahulbamnuya — COMMENTED** [review]
I have remove copyright duplication

**Comment by hiteashgupta1** [comment]
Resolve conflicts

**Comment by ANSHIKA-26** [comment]
closing PR due to no response

**Pull request closed without merging**
