### PR TITLE
Added security to the password

### PR DESCRIPTION
**Pull request by sindhuja184**
Solved the issue https://github.com/ANSHIKA-26/WordWise/issues/382, added the promised features.
The features are:

Would continue the rule that the length of the password should be 6 or more
Make sure that password contains combination of uppercase letters, lower case letters, digits, special characters.
Make sure that commonly used passwords are not used.
No sequence of characters.(Eg : abcd, 1234)
image
Solved issue #382 
Continuing the pr conversation #401 

Thanks @ANSHIKA-26, @hiteashgupta1

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Share video how it is showing on the website

**Comment by ANSHIKA-26** [comment]
fixes #382

**Comment by sindhuja184** [comment]
@hiteashgupta1, I will share the video as soon as possible.

**Comment by sindhuja184** [comment]
Hey @ANSHIKA-26, @hiteashgupta1 
To showcase these features I have added a message box,
Features:
Would continue the rule that the length of the password should be 6 or more
Make sure that password contains combination of uppercase letters, lower case letters, digits, special characters.
Make sure that commonly used passwords are not used.
No sequence of characters.(Eg : abcd, 1234)
The password used is abcABC@123

image
The video and the screenshot of the sample output are sent.

Hope u like it, I am open to make changes 

Sorry I am unable to share the video(on github), will mail you instead.

This fixes issue #382

**Comment by sindhuja184** [comment]
Recording 2024-10-07 104919.mp4
<https://drive.google.com/file/d/1A0kfg02jNOPk5BxbYsLS-eRLBxM1WxU0/view?usp=drive_web>
Hey,

Sent the video as mentioned in the pull request #433 solving the issue
#382, Git Hub was not accepting the video format so sent you via mail.

Hope you like it, I am open to making changes.

Regards Sindhuja.

**Comment by sindhuja184** [comment]
image
Image

**Comment by sindhuja184** [comment]
image
Image

**Comment by hiteashgupta1** [comment]
@sindhuja184 Video is not showing it's asking for access
Kindly add video here

**Comment by ANSHIKA-26** [comment]
merge conflicts

**Comment by sindhuja184** [comment]
Hey @ANSHIKA-26, @hiteashgupta1 

As the conflict was arising due a space in the main file, I had no other option other than push force. It resolved conflicts.
First I had upstream by repo from your repo so that I can get latest version of your repo, then I added my changes and push force.

Hope you understand

**Comment by sindhuja184** [comment]
Will I be allocated the points.
If problem persists please inform I will reopen the pull request

**Pull request closed without merging**
