### PR TITLE
Solved issue number #661 : In the phone number box digits are exceeds from 12 digits

### PR DESCRIPTION
**Pull request by Mayanksaininh**
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .
Screenshot (10)

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by hiteashgupta1** [comment]
@Mayanksaininh are you working on this

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by ANSHIKA-26** [comment]
This branch has conflicts that must be resolved

**Comment by Mayanksaininh** [comment]
Ma'am please give me some time I will solve this

**Pull request closed without merging**
