### PR TITLE
added a simple and good pre loader

### PR DESCRIPTION
**Pull request by rahulkumarparida**
# preview
Screenshot 2024-10-08 185748
**i hope you understand my work and provide me a level in for gssoc extd 2024**

### CODE REVIEW

**Comment by rahulkumarparida** [comment]
@ANSHIKA-26  i request you to at least provide a level 1 gssoc extd to me as my first please i am requesting you for my work 
i hope you understand

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by rahulkumarparida** [comment]
> issue number ?

Adding a pre-loader #577

**Comment by ANSHIKA-26** [comment]
fixes #577

**Pull request merged**
