### PR TITLE
Slider images

### PR DESCRIPTION
**Pull request by aditiverma-21**
### Pull Request Checklist
image

- [ ] I have added screenshots to show the working of my code.
- [ ] added the optimized feature.

### CODE REVIEW

**Comment by aditiverma-21** [comment]
Please check the updates.

**Comment by hiteashgupta1** [comment]
This branch has conflicts

**Comment by aditiverma-21** [comment]
@ANSHIKA-26 Could you please review the pull request when you get a chance? Thanks!

**Comment by ANSHIKA-26** [comment]
@aditiverma-21 what changes have you done exactly ? Kindly explain , also add before and after screenshots of the feature

**Comment by aditiverma-21** [comment]
> @aditiverma-21 what changes have you done exactly ? Kindly explain , also add before and after screenshots of the feature

okayy

**Comment by aditiverma-21** [comment]
image
this was the before image I posted a issue on this named IMAGE BUG 
and the after image...

image
The issue was the images were not correctly working so I added the slider feature

**Comment by aditiverma-21** [comment]
@hiteashgupta1 can you add gssoc label to this pr?

**Comment by hiteashgupta1** [comment]
@aditiverma-21 can you add slider image feature on latest fork repo as you have added previously
Kindly refork and resync from the latest repo and add again

**Comment by aditiverma-21** [comment]
Yes sure

**Pull request merged**
