### PR TITLE
added about us page info

### PR DESCRIPTION
**Pull request by Aditi2k5**
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Kindly follow pr checklist

**Comment by Aditi2k5** [comment]
image before
Screenshot 2024-10-12 182732
after
fixed issue #839

**Comment by Aditi2k5** [comment]
Hi I have added screenshots in the comments, kindly check if correct
________________________________

**Comment by hiteashgupta1** [comment]
Mention issue number

**Comment by Aditi2k5** [comment]
Issue #674
________________________________

**Pull request merged**
