### PR TITLE
Email link

### PR DESCRIPTION
**Pull request by Adityakashyap1011**
Email link added to every page

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Have you reforked and resync from latest repo

**Comment by Adityakashyap1011** [comment]
Yes

**Comment by hiteashgupta1** [comment]
Kindly share screenshot before and after what you have done

**Comment by Adityakashyap1011** [comment]
Screenshot 2024-10-05 090602
Before clicking on the email would not lead to any further actions



Screenshot 2024-10-05 090617

Screenshot 2024-10-05 090707
But now clicking on the email or icon leads to a page where user can mail directly to the organization

**Pull request merged**
