### PR TITLE
Changed the CSS styling and hovering the page with additional features #1587

### PR DESCRIPTION
**Pull request by Ashmitha2606**
### Pull Request Checklist #1587 

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
the footer looks different on every page , kindly make it same on all pages by changing all footers to this -
image
great design !

**Comment by ANSHIKA-26** [comment]
if you can fix this as footer for all pages , then will give you a level 2 for it

**Comment by Ashmitha2606** [comment]
Ok sure !! Will make the changes

**Comment by Ashmitha2606** [comment]
Done the changes

**Comment by hiteashgupta1** [comment]
Resolve conflicts

**Comment by Ashmitha2606** [comment]
Hey hii I have sent a new pull request in which there are no conflicts as
you asked also modified footer for every page

**Pull request closed without merging**
