### PR TITLE
Added login with google and facebook options which are completely functional

### PR DESCRIPTION
**Pull request by sania-2912**
I have added third party authentication to the login pages which will make it easy for users to login.

Fixes#1596

https://github.com/user-attachments/assets/74379a8b-d14f-4b77-b0cb-930f243253a3

- [X ] I have added screenshots and videos to show before and after the working of my code.
- [ X] I have ensured that the screen size is set to 100% while making the video.
- [ X] I have synced the latest fork with my local repository and resolved any conflicts.
- [ X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ X] I understand that if any the above conditions are not met , my PR will not be MERGED .

i hope the contribution make is substantial and useful!

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
hey , we do not use login.html for login , we like the current design

**Comment by ANSHIKA-26** [comment]
image
this is where we have login with google , which is currently working , if you wish to contribute , feel free to add a login by facebook option here , also please delete these login.html and signup.html files , these are stray , we do not wish to implement them 
Thanks

**Comment by sania-2912** [comment]
alright, theses pages were already existing so i added the aouth implementation to them. however i will change it. shall i delete the PR then?

**Comment by sania-2912** [comment]
@ANSHIKA-26 please check PR#1617

**Pull request closed without merging**
