### PR TITLE
Feature footer category

### PR DESCRIPTION
**Pull request by vinit105**
Screenshot 2024-10-02 204856
Screenshot 2024-10-02 204926
### Pull Request Checklist

- [x] I have added screenshots and videos to show the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
can you please show before : after images of what changes you have done ?

**Comment by vinit105** [comment]
Screenshot 2024-10-02 174109

This was the older footer, i changed to responsive footer

### offtopic
- Please create the folders for all the features
like in JS folder only the functionality and There is a lot of CSS file lines, I was not able to fork it as well, 35mb files
and for each components create the  folder for the html files

**Comment by ANSHIKA-26** [comment]
your code has merge conflicts

**Comment by ANSHIKA-26** [comment]
This branch has conflicts that must be resolved

**Comment by hiteashgupta1** [comment]
Are you working on this issue

**Comment by vinit105** [comment]
Sorry, nope There has been a lot of complexity with my code and GitHub push

**Pull request closed without merging**
