### PR TITLE
ADDED Cursor Animation of INDIAN TRICOLOR Theme

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
ADDED Cursor Animation of INDIAN TRICOLOR Theme

BEFORE : (Normal Cursor)

     AFTER : 
https://github.com/user-attachments/assets/38ab1d9e-b894-46f4-848b-c3d776b2eb8a

### Pull Request Checklist

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@ANSHIKA-26 Please Review My Changes and Merge it by Assigning Labels to it !!!

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by PatelHarsh2006** [comment]
@ANSHIKA-26 Sorry Mam, Not Issued Yet ! But Please Don't Close it !!

**Comment by PatelHarsh2006** [comment]
@ANSHIKA-26 Video have been Uploaded So Please Review My Changes and Merge it by Assigning Labels to it !!!

**Comment by ANSHIKA-26** [comment]
@PatelHarsh2006 kindly understand the procedure of this program just because you have uploaded video doesnt mean the PR will be merged , I never liked cursor animation , i like my website simple , you should have made an issue about the same first and waited for it to be assigned !

**Comment by ANSHIKA-26** [comment]
Thank you for your contribution, but I’ll be closing this PR. As I’ve mentioned before, I prefer to keep the site simple without any cursor animations. Had an issue been raised first, I would have noted this right away, just as I’ve closed previous issues and PRs related to cursor animations. Please make sure to follow the contribution guidelines and wait for an issue to be assigned before working on it. This helps avoid unnecessary work and keeps the project on track. Thanks for your understanding

**Comment by ANSHIKA-26** [comment]
@PatelHarsh2006 if you had gone through some closed issues you can clearly see : 
all cursor animation issues are closed since its not needed - for example - 
https://github.com/ANSHIKA-26/WordWise/issues/1754

**Pull request closed without merging**
