### PR TITLE
contact us issue solved : Contact us backend frontend working correctly #837 done

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
contact us issue solved : Contact us backend frontend working correctly. #837 done

again contact us
env

#To create a passkey on the phone or computer you’re on:

1. Go to https://myaccount.google.com/signinoptions/passkeys.
2. Tap Create a passkey and then Continue.(You'll be required to unlock your device.)
3. A 16 character passkey is generated which you can use.

### Pull Request Checklist

- [ 1] I have added screenshots and videos to show before and after the working of my code.
- [1 ] I have ensured that the screen size is set to 100% while making the video.
- [1 ] I have synced the latest fork with my local repository and resolved any conflicts.
- [1 ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ 1] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
resolve conflicts and mention issue number

**Comment by VinayLodhi1712** [comment]
issue number is already in first line #837 and merge conflict is solved.

**Comment by hiteashgupta1** [comment]
@VinayLodhi1712 It's not working kindly check properly and add footer at the end of page

**Comment by VinayLodhi1712** [comment]
@ANSHIKA-26 and @hiteashgupta1 I have checked now it is working fine. I have added footer also on that page.

some things you need to do while checking its functionality -
1. add that email here on that you want response in server.js (currently i use an email id from your github profile"
emailadd

2. add SMTP email and passkey in .env file.
376024038-7df407f3-4b86-4399-8dc5-a45ee18c8abc
ALSO if possible make it level 3 if possible for you.

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26 kindly check

**Comment by ANSHIKA-26** [comment]
working ! good job

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review it

**Review by MastanSayyad — COMMENTED** [review]
Its fine

**Pull request merged**
