### PR TITLE
[FIX] Nav Bar linkes and jumping fixed

### LINKED ISSUE #220: [BUG] Bad hover effect on nav bar
**Describe the bug**
BAd hover effect on nav bar

**To Reproduce**
1. Go to homepage
2. See error

**Expected behavior**
light and standard effect should be there.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by 4F24L**
## Bugs Fixed
- Fixes #220 
- Nav Bar hover effect fixed
- nav links jumping fixed
- login / sign up hover fixed
- Logo link set to homepage

## Before : 
- Nav links were jumping on hover
- login / signup had no hover effect
- No link on logo 

https://github.com/user-attachments/assets/357b1e59-ea0e-43c1-be97-615b5f76731f

## After ✅ : 
- Nav links were jumping on hover [ FIXED ]
- login / signup had no hover effect [ ADDED ]
- Link added to logo 

https://github.com/user-attachments/assets/40b04b1c-b9d5-4b2f-910c-cac9259ca3b3

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Resolve conflicts resync

**Comment by 4F24L** [comment]
Resolved

**Comment by hiteashgupta1** [comment]
Can you make it light colour hover

**Comment by 4F24L** [comment]
Light border ? Or add a light background?

**Comment by ANSHIKA-26** [comment]
and also just to confirm , click on all the buttons present in the navbar ( just to confirm the redirection is working )  while making the new video with a slight color change when you hover over navbar elements

**Comment by ANSHIKA-26** [comment]
> Light border ? Or add a light background?

background works

**Comment by 4F24L** [comment]
Okay !!

**Comment by 4F24L** [comment]
- Start writing section isn't available 
- All other links are working

https://github.com/user-attachments/assets/5bf1d8fb-727f-4c84-a0a4-8bfb28fec442

**Comment by hiteashgupta1** [comment]
#218 already assigned

**Comment by 4F24L** [comment]
> #218 already assigned

Okay

**Comment by 4F24L** [comment]
@hiteashgupta1 linked issue of this PR is labeled as level2. Can you please add level2 to this PR !!

**Pull request merged**
