### PR TITLE
Enhanced Navbar design by giving clean look

### PR DESCRIPTION
**Pull request by shivam8112005**
### Pull Request Checklist
Fixes: #1320
- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

Before:
Screenshot 2024-10-23 170306
After:
Screenshot 2024-10-24 005721

### CODE REVIEW

**Comment by shivam8112005** [comment]
hey @ANSHIKA-26  is this allright?

**Comment by ANSHIKA-26** [comment]
could you make the headings a little bolder ?

**Comment by ANSHIKA-26** [comment]
and increase the text size a little

**Comment by shivam8112005** [comment]
which heading?

**Comment by shivam8112005** [comment]
text size of navlinks?

**Comment by shivam8112005** [comment]
done?

**Pull request merged**
