### PR TITLE
Enhanced Submit Button fixes issue number #303

### PR DESCRIPTION
**Pull request by Jazz-45**
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### Before 
Screenshot 2024-10-07 121652
Screenshot 2024-10-07 121659

### After
Screenshot 2024-10-07 121710
Screenshot 2024-10-07 121718

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
follow each point of the PR checklist

**Comment by Jazz-45** [comment]
> follow each point of the PR checklist

Sure mam.

**Comment by ANSHIKA-26** [comment]
resolve conflicts

**Comment by Jazz-45** [comment]
> resolve conflicts

Resolved all the existing conflicts.

**Comment by hiteashgupta1** [comment]
fixes #303

**Pull request merged**
