### PR TITLE
BUG: Update twitter icon

### LINKED ISSUE #1222: BUG: Old Twitter icon
**Describe the bug**
In footer of website i found old twitter icon which is not updated by current twitter icon. 

**To Reproduce**
1. Go to footer
2. Edit the twitter icon

**Expected behavior**
Replace the old twitter icon to the current twitter icon.

**Screenshots**

old

@ANSHIKA-26 Please assign  this issue to me:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #1222 Update old twitter icon:)

twitter2

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by harshbhar0629** [comment]
@ANSHIKA-26 Please review my PR and merge with labels:)

**Comment by ANSHIKA-26** [comment]
is it fixed in footer of all pages ? kindly show video

**Comment by harshbhar0629** [comment]
Ok i will edit and provide video to you

**Comment by harshbhar0629** [comment]
@ANSHIKA-26 Please review and merge it:)
Video:) 

https://github.com/user-attachments/assets/0adf61a2-1abb-489e-9aa7-05d064dc6c31

**Comment by harshbhar0629** [comment]
I do erase any code in my vscode when we use ctrl+c and ctrl+v then it format whole page thats why these changes show here:)

**Comment by ANSHIKA-26** [comment]
sync fork once , ig your fork is old

**Comment by harshbhar0629** [comment]
@ANSHIKA-26 Everything is fine now please merge it:)

**Comment by ANSHIKA-26** [comment]
@harshbhar0629 everything is not fixed , while solving merge conflicts you removed webp images and added png ones , we need webp format only , kindly refork , resync , and then make new PR , in this PR you have changes things which were not even necessary , kindly restrict your code to only changing an icon!

**Comment by ANSHIKA-26** [comment]
i would honestly recommend you to either make a new branch from the latest fork , then redo the changes that you have done and make a PR !

**Comment by harshbhar0629** [comment]
Ok i will

**Pull request closed without merging**
