### PR TITLE
Backend created!✨(issue #256)

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

@ANSHIKA-26  please have a look at this.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
the current code will store data in localstorage of the website

**Comment by hiteashgupta1** [comment]
Share a video how it is implemented in the website

**Comment by T-Rahul-prabhu-38** [comment]
sure

**Comment by ANSHIKA-26** [comment]
> we can not create a complete backend because its written in just HTML , one suggestion as of now is can we convert the codebase to either ejs or react , however react will be more preferred. I can work on that as well. Because only with .hbs or .ejs or .jsx u can make a proper backend.

@T-Rahul-prabhu-38 react works , if you wish to migrate the whole website to react , thats cool too , just create a frontend folder and add files to it , (.jsx ) would be ideal .

**Comment by ANSHIKA-26** [comment]
please resolve merge conflicts

**Comment by T-Rahul-prabhu-38** [comment]
conflicts have been resolved.

**Comment by ANSHIKA-26** [comment]
could you attach a little video showing the working as well

**Comment by T-Rahul-prabhu-38** [comment]
sure ill do that in sometime

**Comment by T-Rahul-prabhu-38** [comment]
https://github.com/user-attachments/assets/8543efe3-ced8-4fd9-be7f-98b5d2543fea

the user details will be stored in the local storage.and from there u can retrive it aswell as store JWts

**Pull request merged**
