### PR TITLE
Fixed issue#656:Icons in the Categories Page Bottom are not properly spaced

### PR DESCRIPTION
**Pull request by Arghya-Chakraborty0812**
### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

After:
 
Screenshot 2024-10-09 at 11 31 00 PM

Before:

image

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
fixes #656

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by hiteashgupta1** [comment]
Sync fork 
And add twitter icon also

**Comment by ANSHIKA-26** [comment]
issue fixed in some other PR

**Pull request closed without merging**
