### PR TITLE
updated NavBar 

### PR DESCRIPTION
**Pull request by Priyanshi231**
### Pull Request Checklist

- [x] I have added screenshots and videos to show the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.

image

solved the issue #150

### CODE REVIEW

**Comment by Priyanshi231** [comment]
Thankyou so much

**Comment by hiteashgupta1** [comment]
@Priyanshi231 you are supposed to make this button working

**Comment by Priyanshi231** [comment]
@hiteashgupta1 Ok I will do it in 2 days

**Comment by Priyanshi231** [comment]
@hiteashgupta1 The work has been done, you can check it in pull request #239

**Comment by Priyanshi231** [comment]
@hiteashgupta1 The work has been done kindly check the pull request #239

**Pull request merged**
