### PR TITLE
Recreated Animated sign in and sign up page : Issue no #293

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
### Before
Before Login

### After
https://github.com/user-attachments/assets/9abe41f0-91fc-49a6-a989-ed2680464466

Sign up wordwise

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by AbhijitMotekar99** [comment]
Hey @hiteashgupta1 @ANSHIKA-26 
I have successfully recreated the Login and Signup pages with added animations. If it’s possible, could you please assign a Level 3 label for this contribution?

**Comment by hiteashgupta1** [comment]
#274 already there 
@ANSHIKA-26

**Comment by hiteashgupta1** [comment]
@AbhijitMotekar99 have you added login validation

**Comment by ANSHIKA-26** [comment]
it looks great @AbhijitMotekar99 but since #274 is also there , lets give them a chance to make the ui as well , will merge whatever is better , good job tho !

**Comment by AbhijitMotekar99** [comment]
Hey @ANSHIKA-26 
Thank you for the feedback! I understand the importance of giving everyone a chance, but I put in a significant amount of time to create this UI. I believe it meets the requirements well. I suggest merging mine for now, and if #274's submission turns out to be superior, we can always switch to that. Looking forward to your thoughts!

**Comment by hiteashgupta1** [comment]
If #274 not made pr timely then this changes will be merged
In the meantime you can add integration of login through backend as there is already backend added in #292

**Comment by AbhijitMotekar99** [comment]
Ok , no problem 
I also have one request regarding PR #225. It was merged without any label, and I dedicated a lot of time to that issue. I left a comment there but haven't received a response yet. Could you please review it and consider adding the appropriate label?"

**Comment by hiteashgupta1** [comment]
@AbhijitMotekar99 Go further after #276

**Comment by ANSHIKA-26** [comment]
PR #330 already been created , since the issue was raised by them first ,it needs to be merged , good job though !

**Pull request closed without merging**
