### PR TITLE
Upgraded overall UI of main page : issue no 47

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
## Before 
Screenshot 2024-10-04 142405

## After
cards

### Pull Request Checklist

- [x] I have added screenshots and videos to show the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.

### CODE REVIEW

**Comment by AbhijitMotekar99** [comment]
Hey @ANSHIKA-26,
Please give **Level 3 label** because,
I have significantly improved the overall UI and recreated the entire header file, which required some advanced effort. Given the complexity of these changes, I kindly request you to label this PR with **level 3.**


Add gssoc-ext  , Hactoberfest-accepted label.

**Comment by ANSHIKA-26** [comment]
This branch has conflicts that must be resolved

**Comment by AbhijitMotekar99** [comment]
> This branch has conflicts that must be resolved
I resolved all conflict now you can merged

**Comment by AbhijitMotekar99** [comment]
I resolved All the conflicts now you can merged

**Comment by hiteashgupta1** [comment]
This issue has already been merged

**Pull request closed without merging**
