### PR TITLE
fixing the footer to perfect #86

### PR DESCRIPTION
**Pull request by sahhoArjun097**
fixing the footer to perfect #86 
added responsiveness to the footer and make the changes in the styling 

https://github.com/user-attachments/assets/7874e4ae-9ded-4b0f-a6b5-bec8b6738e49

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
kindly sync fork

**Comment by sahhoArjun097** [comment]
ok

**Comment by ANSHIKA-26** [comment]
your code has merge conflicts

**Comment by sahhoArjun097** [comment]
https://github.com/user-attachments/assets/3f1c2769-2281-4b4a-aab3-cc735bc1aca7

**Pull request closed without merging**
