### PR TITLE
Newsletter added and Footer modified

### PR DESCRIPTION
**Pull request by DBasu2610**
I have added a Newsletter which is associated with a subscribe button once a user enters his email address.

Furthermore I added the Authentication Copyright at the Footer section which would definitely ensure the authenticity of WordWise.

Please check out the snippets below for both the modifications

nl

ca

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
share a video showing full screen , kindly follow PR checklist

**Comment by DBasu2610** [comment]
Yes Here is the full screen video

https://github.com/user-attachments/assets/36eb01c0-8693-4a47-bf65-a9d162d078d5

**Comment by hiteashgupta1** [comment]
There is lot of spacing between newsletter and footer section kindly do changes properly

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by hiteashgupta1** [comment]
Share video after changes

**Comment by DBasu2610** [comment]
This is it after reducing the spacing between the Newsletter and the Footer
https://github.com/user-attachments/assets/03a115e8-ff95-47b3-a357-4140c3c0ddf3

**Pull request merged**
