### PR TITLE
REMOVED "GIVE FEEDBACK", Changed the text below "CONTACT US", Added Subject & Priority (High/Low) in the Get in Touch form.

### PR DESCRIPTION
**Pull request by harshit1arora**
REMOVED "GIVE FEEDBACK", Changed the text below "CONTACT US", Added Subject & Priority (High/Low) in the Contact Us/Get in Touch form. The screenshots are attached here for your reference.

SUB PRIORITY
GIVE FEEDBACK REMOVE

### CODE REVIEW

**Comment by harshit1arora** [comment]
@ANSHIKA-26 Kindly have a look and let me know.

**Comment by harshit1arora** [comment]
Fixed #255

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by harshit1arora** [comment]
> sync fork

@ANSHIKA-26 done

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
> @ANSHIKA-26

lets wait for issue #266  to make a pr , if its not made soon , we merge this

**Comment by ANSHIKA-26** [comment]
@harshit1arora in that case , once #266 is made , your PR can still be merged to reflect the subject & priority changes you have done , so kindly wait a bit

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by ANSHIKA-26** [comment]
@harshit1arora kindly resolve merge conflicts

**Comment by ANSHIKA-26** [comment]
closing PR due to lack of response , do raise another PR if you wish to continue , we are still open to suggestions !

**Pull request closed without merging**
