### PR TITLE
img centerd and previewed

### PR DESCRIPTION
**Pull request by Pratikpawar13**
I had kept images in boxes which are vertically and also horizontally centered .
Also on clicking on img image preview will open on separate window.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
kindly share relevant screenshots

**Comment by Pratikpawar13** [comment]
I had kept images in boxes which are vertically and also horizontally centered .
Also on clicking on img image preview will open on separate window.

**Image centered**
Screenshot 2024-10-02 172519


**Image open on new window**
Screenshot 2024-10-02 172726


where A in image is original website and B is a preview of image on new tab.

**Comment by hiteashgupta1** [comment]
The files has conflicts that must be resolved

**Comment by hiteashgupta1** [comment]
Refork the pull request

**Pull request closed without merging**
