### PR TITLE
Add the comment box  #1514

### PR DESCRIPTION
**Pull request by mansi066**
I have add the comment section page as I raise the issue and make change in all the slides
Fixes: #1514
### Pull Request Checklist

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .
Before: On clicking on comment button it is not working
Screenshot 2024-10-28 200653
After: On clicking on comment button another comment section page  open as shown in video clip.
Screenshot 2024-10-29 200842

https://github.com/user-attachments/assets/4eb07b1f-15a6-4085-9ead-be84f60574c6

@ANSHIKA-26 Please review my change  and let me know if you want any changes
in my 2nd commit I have add the last PRs  that you merge 6 hours ago as it was not added my main code that I was forked

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
hey , nice work , its just the user is displayed under random names every time we open a comment box

**Comment by ANSHIKA-26** [comment]
also could you make a bit according to our theme ? background colors and font need changing

**Comment by mansi066** [comment]
ok

**Comment by mansi066** [comment]
@ANSHIKA-26 I have made changes please review it

**Comment by mansi066** [comment]
Light mode:
https://github.com/user-attachments/assets/f29fa02a-44e0-46a8-b544-4d8ea6e275af
Dark mode:

https://github.com/user-attachments/assets/d72a1ac6-328e-428a-99fd-a2b34df68b29

**Comment by ANSHIKA-26** [comment]
conflicts

**Comment by ANSHIKA-26** [comment]
resolve conflicts , refork , resync , follow PR checklist and make a new pr

**Pull request closed without merging**
