### PR TITLE
Fixed misalignment of buttons in Navbar issue ! #1073

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #1073
Issue Fixed(In Feedback page) -

Before-
Screenshot 2024-10-17 001637

After-
Screenshot 2024-10-17 120847
Screenshot 2024-10-17 121226

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
hey , there are some more issues with the navbar icons , can you fix them too ?

**Comment by Subhajit-2023-44** [comment]
> hey , there are some more issues with the navbar icons , can you fix them too ?

**Comment by Subhajit-2023-44** [comment]
> hey , there are some more issues with the navbar icons , can you fix them too ?

home page issue ? #1094 ??

**Comment by Subhajit-2023-44** [comment]
> hey , there are some more issues with the navbar icons , can you fix them too ?

Okay wait I'll give another PR..

**Pull request closed without merging**
