### PR TITLE
Fixed icons color issue in Leading Blog page ! #735

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #735 

Screenshot 2024-10-11 161425
Screenshot 2024-10-11 161415

PA @ANSHIKA-26 

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
@Subhajit-2023-44 make heading Travel also better color in dark mode

**Comment by hiteashgupta1** [comment]
And do some work on profile icon it is also get invisible in dark mode

**Comment by Subhajit-2023-44** [comment]
@hiteashgupta1 PA I have already submitted an assign request #777 with this issue along with 2 other issues.    
Do I still solve it here?    Then assign me for the remaining two Issue. #777

Please check it

**Comment by hiteashgupta1** [comment]
Do changes here

**Comment by Subhajit-2023-44** [comment]
@hiteashgupta1 PA why did you close my assign request for all three issues?   Shall I fix the all three issues here?

**Comment by hiteashgupta1** [comment]
Yes as it is regarding ui

**Comment by hiteashgupta1** [comment]
Take your time and make it good and interactive

**Comment by Subhajit-2023-44** [comment]
Okay PA @hiteashgupta1 I'm solving all these issues properly.

**Comment by hiteashgupta1** [comment]
But also check from the live website as recently changes are made on blog.html file

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by Subhajit-2023-44** [comment]
okay

**Comment by Subhajit-2023-44** [comment]
okay

**Comment by Subhajit-2023-44** [comment]
PA @hiteashgupta1 I'm solving all these issues properly ..

**Comment by Subhajit-2023-44** [comment]
PA @hiteashgupta1 #811 please check it

**Pull request closed without merging**
