### PR TITLE
Added styling and relevant effects to cards

### PR DESCRIPTION
**Pull request by 770navyasharma**
#65 issue resolved

### CODE REVIEW

**Comment by 770navyasharma** [comment]
Please also add hacktoberfest , gssoc-ext tags along with level

**Comment by ANSHIKA-26** [comment]
kindly attach relevant screenshots

**Comment by 770navyasharma** [comment]
Yes suree
Screenshot 2024-10-02 at 9 24 05 PM
Screenshot 2024-10-02 at 9 25 00 PM

**Comment by hiteashgupta1** [comment]
Kindly check the files

**Comment by hiteashgupta1** [comment]
Checks are failed

**Pull request closed without merging**
