### PR TITLE
issue  #1169 Fix the issue in  give_feedback page where it is not visible

### PR DESCRIPTION
**Pull request by toshankanwar**
hello @ANSHIKA-26 

the issue no #1169 
I have Fix the issue in feedbvack page where it is not visible due to some errors
image
before it is looking empty

image
After that i added this 

image
And now it is working 

Thankyou

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
@toshankanwar can you just search the code for existing feedback page ? it was already there for dark and light mode , the page you have made is nice too , its just the existing one was ready to use

**Comment by ANSHIKA-26** [comment]
if possible kindly restore the page that was there earlier

**Comment by toshankanwar** [comment]
> if possible kindly restore the page that was there earlier

@ANSHIKA-26 the page that was earlier has some bugs. what bugs are their it is hard to identify as all code is looking good and their is no mistake. but what are the reasons that the page is not visible in webpage that was the reason i made new feedback page.

thankyou

**Comment by toshankanwar** [comment]
> @toshankanwar can you just search the code for existing feedback page ? it was already there for dark and light mode , the page you have made is nice too , its just the existing one was ready to use

ya sure i search for it 
thankyou for your feedback and support

**Comment by ANSHIKA-26** [comment]
maybe its not linked properly or the link somehow has some . or # , try looking into the navbar instead of looking into code of feedback page , that might help

**Comment by toshankanwar** [comment]
> maybe its not linked properly or the link somehow has some . or # , try looking into the navbar instead of looking into code of feedback page , that might help

@ANSHIKA-26  I checked many times to navbar . Navbar has no issue to redirect into the page . the feedback pages code is also not working on other pages of I copy and paste the code to new html file . I tried this with many experiment thats why I need to change the feedback page

Thankyou

**Comment by ANSHIKA-26** [comment]
okay then fix the feedback page for dark mode , improve Ui

**Comment by toshankanwar** [comment]
hello @ANSHIKA-26 
issue #1169 
i have solve the issue, added dark mode and adjust UI and solve the conflicts problem

https://github.com/user-attachments/assets/51147f82-3449-4f3f-aef5-deb1fd018449
all details are in above video 
here i attach screenshots also
image
image
image

thankyou for attention and support

**Comment by ANSHIKA-26** [comment]
perfect !

**Comment by toshankanwar** [comment]
> perfect !

thanks @ANSHIKA-26  can you please upgrade level 2 to level 3 🥺. i have some targets to complete in this month only. so please if you can do this .

thanks

**Pull request merged**
