### PR TITLE
change of about section

### PR DESCRIPTION
**Pull request by DarakshanSaara**
### Pull Request Checklist
Fixed issue #170 
- [x] I have added screenshots and videos to show the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Add screenshots of what you have done

**Comment by DarakshanSaara** [comment]
Screenshot 2024-10-04 185014
Screenshot 2024-10-04 185129

**Comment by hiteashgupta1** [comment]
This branch has conflicts resolve them 
And add screenshots from the live website before and after changes

**Comment by DarakshanSaara** [comment]
Screenshot 2024-10-04 211227
Before

After

**Comment by ANSHIKA-26** [comment]
hello , kindly sync your fork and make a NEW pr if required

**Pull request closed without merging**
