### PR TITLE
Improve text & image alignments done ! #851

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue - #851 

Screenshot 2024-10-16 224405
Screenshot 2024-10-16 224412

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
this looks even weirder than it was before , any other alignment ideas ?

**Comment by Subhajit-2023-44** [comment]
> this looks even weirder than it was before , any other alignment ideas ?

No I don't have any other alignment ideas, sorry PA

please merge and add level

**Comment by Subhajit-2023-44** [comment]
Before - 
Screenshot 2024-10-16 225410

After -
Screenshot 2024-10-16 224412

**Comment by ANSHIKA-26** [comment]
just remove the whole section then , including the trending post button

**Comment by ANSHIKA-26** [comment]
erase the code of this section  , dont comment it

**Comment by Subhajit-2023-44** [comment]
> just remove the whole section then , including the trending post button

Ok wait I'll give another PR..

**Comment by Subhajit-2023-44** [comment]
> just remove the whole section then , including the trending post button

@ANSHIKA-26  done

**Pull request closed without merging**
