### PR TITLE
Fix: Add Backend Processing for Contact Us Form

### PR DESCRIPTION
**Pull request by prashu2507**
This pull request introduces a backend solution for handling "Contact Us" form submissions. The feature enables users to send messages through the form, which are then processed by a PHP script that validates the input and sends an email to the site administrator.

Key Features:

Backend Processing: A new process_contact.php file that processes form data and sends it to an admin email.
Form Validation: Basic email validation to ensure a correct format.
User Feedback: Displays success or failure messages to users based on form submission results.
Files Added:

process_contact.php: The core file handling form submissions.
issue number: 1492

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by ANSHIKA-26** [comment]
we were building a MERN application in backend , it was pretty much visible from the js files present in the backend , why have you added a php file ?

**Comment by prashu2507** [comment]
> we were building a MERN application in backend , it was pretty much visible from the js files present in the backend , why have you added a php file ?

Thanks for clarifying! Since your backend is built with JavaScript in a MERN stack, we should definitely handle the "Contact Us" feature using Node.js and Express instead of PHP.

**Comment by hiteashgupta1** [comment]
#1493

**Pull request closed without merging**
