### PR TITLE
dark mode and the Navbar feature working!

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
### Pull Request Checklist

https://github.com/user-attachments/assets/c0b0c02c-e6f0-4249-a48a-e53ba6db5a92

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@hiteashgupta1  sir can you review this PR.

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by T-Rahul-prabhu-38** [comment]
sir just wanted to confirm , this is level3 right.

**Comment by hiteashgupta1** [comment]
Level 3 is adding backend also

**Comment by hiteashgupta1** [comment]
Keep contributing

**Comment by T-Rahul-prabhu-38** [comment]
sure sir , i wasnt aware of that ill try that aswell

**Pull request merged**
