### PR TITLE
NEW FEATURE : Like Button Added ❤️

### PR DESCRIPTION
**Pull request by AmanPatre**
I have added a  like button in the blog cards . People who likes the blog after reading could hit the like button 

https://github.com/user-attachments/assets/4b788eac-5dc6-47bd-b627-d8639ae6d57d

### CODE REVIEW

**Comment by AmanPatre** [comment]
Please merge this PR I have done a lots of hardwork

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by ANSHIKA-26** [comment]
will surely merge the PR , follow PR template !

**Comment by AmanPatre** [comment]
why You closed my PR

**Comment by ANSHIKA-26** [comment]
follow PR template

**Pull request closed without merging**
