### PR TITLE
Updated the Contact Us page UI

### PR DESCRIPTION
**Pull request by SatyaJaiss**
I have updated the UI of the contact us page, the page is looking more attractive, and I also updated the UI of footer section of Contact Us Page
Screenshot 2024-10-03 223842
Screenshot 2024-10-03 223859

### Pull Request Checklist

- [x] I have added screenshots and videos to show the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.

### CODE REVIEW

**Comment by SatyaJaiss** [comment]
@ANSHIKA-26 Kindly review and kindly let me know if you need any changes.

**Comment by ANSHIKA-26** [comment]
kindly sync fork

**Comment by SatyaJaiss** [comment]
> kindly sync fork

@ANSHIKA-26 Could you please explain how to do that?

**Comment by ANSHIKA-26** [comment]
unfork the repo, then fork again , thats an easier way to resync fork !

**Comment by SatyaJaiss** [comment]
Do then I have to do PR again or not?

**Pull request closed without merging**
