### PR TITLE
share button added

### LINKED ISSUE #643: Add share option to website
Can add share option to the website so that a user can share the website to their surroundings, can increase users of our page.

Kindly assign the work to me @ANSHIKA-26 under gssoc'24 extd label

image

### PR DESCRIPTION
**Pull request by PoojaKanagaraj06**
fixes #643 ### Pull Request Checklist
Before

Uploading WordWise - Google Chrome 2024-10-13 11-28-43.mp4…
image

after

Uploading WordWise and 5 more pages - Personal - Microsoft​ Edge 2024-10-13 11-25-36.mp4…
image
image

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
resolve merge conflicts

**Comment by PoojaKanagaraj06** [comment]
@ANSHIKA-26 resolved merge conflicts

**Comment by ANSHIKA-26** [comment]
i still see conflicts

**Comment by PoojaKanagaraj06** [comment]
I have resolved merge conflicts @ANSHIKA-26 
image

**Comment by hiteashgupta1** [comment]
Kindly add share button to index.html
And remove double of file in blog.html

**Comment by PoojaKanagaraj06** [comment]
Ok

**Comment by PoojaKanagaraj06** [comment]
@ANSHIKA-26 @hiteashgupta1 Does my solutionj still showing any issues?

**Comment by hiteashgupta1** [comment]
@PoojaKanagaraj06 you have changed the whole file of blog.html kindly raise new pr and add the button properly in footer without changing the footer
Screenshot_2024_1014_160640

**Pull request closed without merging**
