### PR TITLE
Fix Chrome errors on home page

### LINKED ISSUE #595: Chrome inspect shows errors when loading home page
**Describe the bug**
Chrome inspect shows errors when loading the home page

**To Reproduce**
1. Go to home page
2. Click on refresh
3. Scroll down to console in chrome inspect

**Expected behavior**
No errors should be present 

**Screenshots**
c1

**Additional context**

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
closes #595 

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

---
- Before
b1
- After
b2

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by mehul-m-prajapati** [comment]
> sync fork

@ANSHIKA-26 : okay, done.

**Comment by ANSHIKA-26** [comment]
resolve conflicts @mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
> resolve conflicts @mehul-m-prajapati

@ANSHIKA-26 : okay resolved it. thanks

**Pull request merged**
