### PR TITLE
Center aligned Word Of Day section

### PR DESCRIPTION
**Pull request by AbrerAsif07**
Issue - #1402 
Screenshot 2024-10-26 130456

### Pull Request Checklist

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by AbrerAsif07** [comment]
@ANSHIKA-26 Kindly check Have made the necessary changes. As a beginner ty for this opportunity

**Comment by ANSHIKA-26** [comment]
resolve conflicts

**Comment by AbrerAsif07** [comment]
>[Screenshot 2024-10-26 130456](https://private-user-images.githubusercontent.com/157715929/380372969-00dfba1c-7757-441f-88b7-2ba44dd1d500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTAwMDMsIm5iZiI6MTcyOTk0OTcwMywicGF0aCI6Ii8xNTc3MTU5MjkvMzgwMzcyOTY5LTAwZGZiYTFjLTc3NTctNDQxZi04OGI3LTJiYTQ0ZGQxZDUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzM1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmNjY2Y4MDkxYjUyZjdkYjMzNGFiZTcxMzY3OGMzMzdiNzk5YjBkZTVjZmE2Y2I3MDEwZTFiMmUwNGZiYjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tynfucpEm9QCYRATdrH125IHl8-rlLUAcYpyyXNlms0)
> 
> ### Pull Request Checklist
> * [ ]  I have added screenshots and videos to show before and after the working of my code.
> * [ ]  I have ensured that the screen size is set to 100% while making the video.
> * [ ]  I have synced the latest fork with my local repository and resolved any conflicts.
> * [ ]  I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) )
> * [ ]  I understand that if any the above conditions are not met , my PR will not be MERGED .

**Comment by ANSHIKA-26** [comment]
issue resolved

**Pull request closed without merging**
