### PR TITLE
privacy policy page added fixes issue #662

### PR DESCRIPTION
**Pull request by ShrishtiSingh26**
#662 
Added Privacy Policy Page link in the footer and made a Privacy policy page

This link is present in footer of every page

image
image
image

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
This branch has conflicts that must be resolved

**Comment by ShrishtiSingh26** [comment]
@hiteashgupta1 resolves the conflicts

**Comment by ShrishtiSingh26** [comment]
@ANSHIKA-26 @hiteashgupta1 
I have resolved all the conflicts now, please merge the PR

Thank you for letting me contribute in this project!

**Comment by hiteashgupta1** [comment]
There are still conflicts

**Pull request merged**
