### PR TITLE
fixes #1380 Refactor social links styling

### LINKED ISSUE #1380: Non-Visibility of the X logo when switched to dark mode
**Describe the bug**

When switched to dark mode the logo of the X is not visible

**To Reproduce**
1. Go to Footer
2. Click on Dark Mode switch
3. See error

**Expected behavior**

There should be a background of white to show the logo perfectly

**Screenshots**
{6D08D9B8-7715-4DDC-AC41-0A34C7B560CC}

{0EE6E55F-8014-4FF9-92AC-286195A7C200}

**Additional context**

### PR DESCRIPTION
**Pull request by harjasae2001**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

https://github.com/user-attachments/assets/4041969c-4fc4-4ea6-a758-36976f94c0ef

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
resolve conflicts

**Comment by harjasae2001** [comment]
Done.

**Comment by ANSHIKA-26** [comment]
why is there no twitter icon on leading blog page ?

**Comment by harjasae2001** [comment]
I fixed it in my code but that causes conflicts with the code.

**Comment by harjasae2001** [comment]
## In my code it is working as fa-x-twitter icon is not working on blog.html page. So I have to replace it with fa-twitter icon and that is causing the conflicts.
{8EA64E6E-B993-45D2-840D-FACFC3FE1535}

**Comment by ANSHIKA-26** [comment]
try again , refork ,resync and open a new PR , we cannot add old twitter icon !

**Pull request closed without merging**
