### PR TITLE
Added password strength validation to signup page

### PR DESCRIPTION
**Pull request by jvkousthub**
### Pull Request Checklist

image
image
image
image

Fixes : #767 

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Kindly follow pr checklist

**Review by hiteashgupta1 — APPROVED** [review]

**Comment by jvkousthub** [comment]
> Kindly follow pr checklist

Updated

**Comment by jvkousthub** [comment]
@ANSHIKA-26 @hiteashgupta1 please let me know if any changes are required

**Comment by hiteashgupta1** [comment]
Kindly refork you having old blog.html file

**Pull request merged**
