### PR TITLE
Improve mobile responsiveness of navbar

### PR DESCRIPTION
**Pull request by shivhere007**
Fix Issue #1371 
Improved the responsiveness of the navbar in mobile view to enhance user experience.
Screenshot 2024-10-25 010500

### Pull Request Checklist

- [ ] I have added screenshots to show the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
its not fixed for a lot of screen sizes , can you please do that ?

**Comment by ANSHIKA-26** [comment]
see

**Comment by ANSHIKA-26** [comment]
image

**Comment by ANSHIKA-26** [comment]
image

**Comment by shivhere007** [comment]
Navbar is now responsive for all screen sizes.

Laptop view :
Screenshot 2024-10-25 152604

Tablet view :
Screenshot 2024-10-25 152647

Different Mobile views :
Screenshot 2024-10-25 152658
Screenshot 2024-10-25 152713
Screenshot 2024-10-25 152725

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by shivhere007** [comment]
Please check and let me if it's working now or not, I have synced fork.

**Pull request merged**
