### PR TITLE
Add FAQ Section to the WordWise Website

### PR DESCRIPTION
**Pull request by Vishwajeet594**
### Pull Request Checklist (issue #251 )

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .
### Description
**This PR adds a Frequently Asked Questions (FAQ) section to the WordWise website to improve user experience by providing answers to common queries. The FAQ section has been designed to align with the website's theme, enhancing navigation and accessibility for users.**

### Key Features:

**1. Accordion-style FAQ: The questions and answers are organized in a collapsible accordion format to save space and provide a clean, interactive experience.
2. Responsive Design: The FAQ section is fully responsive, ensuring that it works seamlessly across all devices (desktop, tablet, mobile).
3. Updated Content: The FAQ answers commonly asked questions related to the platform’s features, such as switching between themes, creating blog posts, and following topics or authors.**

**1. Navigate to the homepage of the WordWise website.
2. Scroll to the FAQ section.
3. Verify that the accordion functionality works correctly (clicking a question expands/collapses the answer).
4. Check responsiveness across multiple devices (desktop, tablet, and mobile).
5. Ensure that the FAQ content is relevant and easy to understand.**
### Screenshots
**Before: No FAQ section on the website.**
**After:**
Screenshot 2024-10-06 005758

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Show full video where you have added

**Comment by ANSHIKA-26** [comment]
resync your fork

**Comment by Vishwajeet594** [comment]
resync done

**Comment by ANSHIKA-26** [comment]
I have added screenshots and videos to show before and after the working of my code.
 I have ensured that the screen size is set to 100% while making the video.
 
 where is the video ?

**Comment by Vishwajeet594** [comment]
mam my laptop is so old dont support video record i can number of screen shot

**Comment by Vishwajeet594** [comment]
Screenshot 2024-10-06 021042
Screenshot 2024-10-06 021128
Screenshot 2024-10-06 021151

**Review by hiteashgupta1 — APPROVED** [review]

**Pull request merged**
