### PR TITLE
Huge Gap above accordion__wrapper div reduced.

### PR DESCRIPTION
**Pull request by AmanPatre**
I have reduced the gap above accordion__wrapper div . Earlier there was a gap above which was indicating some missing information  .
I reduced the gap by reducing the margin-top of container_1 to 60px instead of 500px.

Please merge this contribution.

Before:

https://github.com/user-attachments/assets/ad5d836b-8692-4223-a441-7ec8187c6656

After:

https://github.com/user-attachments/assets/0ea7018a-70fa-4dac-8dde-d08fc1bfd198

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
resyn fork

**Comment by AmanPatre** [comment]
how to resync the fork ??

**Comment by ANSHIKA-26** [comment]
kindly sync once again

**Comment by AmanPatre** [comment]
resynced please check !

**Pull request closed without merging**
