### PR TITLE
Aditya UI

### PR DESCRIPTION
**Pull request by aditya07389**
## Before :
There was no scroll reveal feature 
## After Adding scroll reveal it looks like this :

https://github.com/user-attachments/assets/3d1f0891-b04e-4244-b0e4-5cbab3e5ae74

2) Added Back to top button :
before there was no back to top feature

## after adding

https://github.com/user-attachments/assets/faea415e-cc89-46cb-8182-8028b07cb1ec

## 3) Signup:

##before :
image
##After :
https://github.com/user-attachments/assets/2800f9ba-5615-4dad-abca-a7d8a1b3c94c

### CODE REVIEW

**Comment by aditya07389** [comment]
hey i have made the changes , @ANSHIKA-26  please review and tell me if thers an issue .

kindly assign level 3 label :)

**Comment by aditya07389** [comment]
@ANSHIKA-26  i have resolved all the conflicts , kindly merge it
 add level 3 tag pls

**Comment by ANSHIKA-26** [comment]
i cannot add level 3 tag , you issue has level 1 tag !

**Comment by ANSHIKA-26** [comment]
image
remove this blue oval border

**Comment by ANSHIKA-26** [comment]
image
remove whatever you have done on sidebar

**Comment by aditya07389** [comment]
i fixed one issue , added scrollrevel and added a back to top button , i atleast deserve level 2 :(

**Comment by aditya07389** [comment]
@ANSHIKA-26 ill remove the oval

**Comment by aditya07389** [comment]
hey @ANSHIKA-26  i have made the changes , please check

**Comment by ANSHIKA-26** [comment]
the sidebar still has some green rectangle border , remove it

**Comment by aditya07389** [comment]
done @ANSHIKA-26  , sorry i didnt realize that , i have made the changes , please check

**Pull request merged**
