### PR TITLE
updating scroll button in main page

### PR DESCRIPTION
**Pull request by ak-0283**
Issue Number #1622
- **"Improved scroll button functionality for smoother user experience."**
- **"Updated scroll button style and fixed alignment issues for better usability."**
- **"Enhanced scroll button responsiveness and design to improve navigation flow."** 

**Screenshot**

Screenshot 2024-11-09 175938.

Please review and merge it @ANSHIKA-26 .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
change the CSS of the button to look like the one on rest of the page s, pink background color etc

**Comment by ak-0283** [comment]
i have updated the colour of scroll button.

**Demo**

Screenshot 2024-11-10 092644

Please review and merge it @ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
image
your button
image
button on rest of the pages
its still different kindly check CSS of existing button and use it to make the new button

**Comment by ak-0283** [comment]
U menan to say that size of other button and mine one is slightly different. I have also checked the color of button was same.

**Comment by ak-0283** [comment]
i have updated the size and hover effect as rest of the pages.

**Attachement**

Screenshot 2024-11-10 132615

Screenshot 2024-11-10 132553

**Comment by ak-0283** [comment]
Please do my code review and merge the pr @ANSHIKA-26 .

**Pull request merged**
