### PR TITLE
Fixed: #789: Made UI changes in the homepage

### PR DESCRIPTION
**Pull request by anshguptasince2004**
Pull Request Checklist
[ ✔️] I have added screenshots and videos to show before and after the working of my code.
[ ✔️] I have ensured that the screen size is set to 100% while making the video.
[ ✔️] I have synced the latest fork with my local repository and resolved any conflicts.
[ ✔️] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) )
[✔️ ] I understand that if any the above conditions are not met , my PR will not be MERGED .
-- As a beginner and newbie to Open-Source Contributions and Gssoc-24, I tried to add value contribution to this project with my tech stack knowledge.

**1.) Changed the navigation bar format with better spacings. -**
Screenshot 2024-10-15 031234
Screenshot 2024-10-15 031246

**2.) Switched the theme change and profile icon button position for a systematic design. -**
Screenshot 2024-10-15 031251

**3.) Changed box shadow effect, transitions and better color selection to the images as based on UI principles.- **
Screenshot 2024-10-15 031251
Screenshot 2024-10-15 031306
Screenshot 2024-10-15 031321

**4.) improved hovering effects on "Load More Posts..." button.- **
Screenshot 2024-10-15 031333

**5.) Added a line before footer to keep it clear.- **
Screenshot 2024-10-15 031344

**6.) Profile Icon dropdown will appear upon hover with better styling.-**
Screenshot 2024-10-15 234001

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
This branch has conflicts that must be resolved

**Comment by ANSHIKA-26** [comment]
kindly resolve conflicts

**Comment by ANSHIKA-26** [comment]
image
make this same as what it is right now , this looks kinda weird

**Comment by anshguptasince2004** [comment]
@ANSHIKA-26 Suggested changes done!

**Comment by anshguptasince2004** [comment]
Suggested change is added.
Screenshot 2024-10-17 022609

**Comment by ANSHIKA-26** [comment]
merge conflicts

**Comment by ANSHIKA-26** [comment]
image
this is what i see... could you record the whole screen and share ?

**Pull request closed without merging**
