### PR TITLE
add website views widget #376

### PR DESCRIPTION
**Pull request by rohitinu6**
### Pull Request Checklist 

Solves issue #376 

Here is the image of the proposed work:

**Before**
image

**After**
image

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

@ANSHIKA-26 Please do let me know if the work needs any changes or update.

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
decrease the size of the widget

**Comment by rohitinu6** [comment]
**Before :**
image


**After :**
image


@ANSHIKA-26 , is this fine?

**Comment by ANSHIKA-26** [comment]
resync your fork , no need for new pr  , this works

**Comment by rohitinu6** [comment]
@ANSHIKA-26 , updated, pls check

**Pull request merged**
