### PR TITLE
login/signup-ui-updated

### PR DESCRIPTION
**Pull request by NK-Works**
### Pull Request Checklist
**Issue #274: Solved**
- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

I have completely update the ui for the login and the signup pop-ups...
image
image
image
image

Video:
https://github.com/user-attachments/assets/662398f3-c3ff-4b28-8190-ceaa4d833abf

I have also made it so that the elements in them change color based on the mode selected by the user...

PS: I also wanted to create a new page for them but someone else opened an issue for that already... if you want i can create an issue for it as well...
I can also implement the signin with google feature in the next issue if you want.
make sure to add the labels...
thanks:)

### CODE REVIEW

**Comment by NK-Works** [comment]
@ANSHIKA-26 here is the updated login and signup ui

**Comment by ANSHIKA-26** [comment]
sync fork

**Comment by NK-Works** [comment]
@ANSHIKA-26 synced..

**Comment by NK-Works** [comment]
@ANSHIKA-26 please make sure to assign level label as only if the level label is mentioned will it be counted.
thanks:)

**Comment by ANSHIKA-26** [comment]
hey can you sync fork again ? also a new video will be required

**Comment by NK-Works** [comment]
@ANSHIKA-26 i resynced it again...
i guess u were merging other pulls or something...
as for the video i will upload it in 5 mins...

**Comment by NK-Works** [comment]
https://github.com/user-attachments/assets/e63be801-7464-4835-a005-0cb7fb606773

@ANSHIKA-26 here is the video

**Comment by hiteashgupta1** [comment]
Have you added validation as it is already in the previous ui
Kindly add it and make full video with validation

**Comment by NK-Works** [comment]
@ANSHIKA-26 i resolved the conflict again... :(

**Comment by NK-Works** [comment]
@hiteashgupta1 @ANSHIKA-26 
here is thre video showing that validation is still working fine...

https://github.com/user-attachments/assets/15885edf-0cfc-4c5c-b4f9-902001200e9b

**Comment by NK-Works** [comment]
@ANSHIKA-26 please add the level label as only the level label in the pull req is counted from what i know:)

**Pull request merged**
