### PR TITLE
i have changed the color

### PR DESCRIPTION
**Pull request by Ash182004**
image
issue no #1446 

### Pull Request Checklist

- [x ] I have added screenshots and videos to show before and after the working of my code.
- [ x] I have ensured that the screen size is set to 100% while making the video.
- [ x] I have synced the latest fork with my local repository and resolved any conflicts.
- [ x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x ] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
make it white

**Comment by Ash182004** [comment]
image

**Comment by ANSHIKA-26** [comment]
conflicts

**Comment by ANSHIKA-26** [comment]
resolve conflicts and make another PR with PROPER FORMAT

**Comment by ANSHIKA-26** [comment]
the color in dark mode should be white , in light mode should be blue , fix and then make new PR

**Pull request closed without merging**
