### PR TITLE
All the pages fixed

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
### Pull Request Checklist
Screenshot 2024-10-05 at 3 56 34 AM
Screenshot 2024-10-05 at 3 56 42 AM

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
this will be considered level2 right.

**Comment by hiteashgupta1** [comment]
Have you reforked after recent commit from repo

**Comment by T-Rahul-prabhu-38** [comment]
yes

**Comment by T-Rahul-prabhu-38** [comment]
i saw a branch conflict , so i reforked it

**Pull request merged**
