### PR TITLE
DOC : README.md Updated #751

### PR DESCRIPTION
**Pull request by purnima2904**
### Description
added repository stats table
created a back to top button at the end
linked code of conduct and contributing file
added forkers and stargazers section
created a featured in section
added better website preview

FIXES : #751 

Screenshot 2024-10-11 184453
Screenshot 2024-10-11 184441
Screenshot 2024-10-11 184430

### Pull Request Checklist

- [x] I have added screenshots and videos to show before and after the working of my code.
- [x] I have ensured that the screen size is set to 100% while making the video.
- [x] I have synced the latest fork with my local repository and resolved any conflicts.
- [x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x] I understand that if any the above conditions are not met , my PR will not be MERGED .

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Comment by hiteashgupta1** [comment]
@ANSHIKA-26

**Comment by ANSHIKA-26** [comment]
add my pinned issues in contribution , just remove the stargazers an forkers , its making the readme too clouded , i want it to be to the point and simple , the main purpose of it should be to brief about project and contribution guidelines

**Comment by purnima2904** [comment]
@ANSHIKA-26 kindly check PR #825 , i have made the requested changes

**Pull request closed without merging**
