### PR TITLE
their are some issues on about page , issue no #504 solved

### PR DESCRIPTION
**Pull request by Hemraj-7**
### Pull Request Checklist

Issue number #504 

## before update
Screenshot 2024-10-07 195918

## after update
Screenshot 2024-10-07 235407

please add these labels gssoc-ext , hactoberfast-accepted and level 2 
this contribution is very hard

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
full screen video showing navbar as well

**Comment by Hemraj-7** [comment]
> full screen video showing navbar as well

i just done work on card

**Comment by Hemraj-7** [comment]
> full screen video showing navbar as well

## i just done work on card, navbar is not completed yet, i will be fix navbar tomorrow

https://github.com/user-attachments/assets/1db49cd4-9062-4aaf-b679-f2a852aa72a8

**Comment by ANSHIKA-26** [comment]
sync fork , someone else did navbar , its not your issue , i just wanted to see the full screen video hence asked for navbar

**Comment by Hemraj-7** [comment]
> sync fork , someone else did navbar , its not your issue , i just wanted to see the full screen video hence asked for navbar

okey

**Comment by ANSHIKA-26** [comment]
solve the conflicts ,go through the code

**Comment by Hemraj-7** [comment]
> solve the conflicts ,go through the code

merge conflict is solved

**Comment by hiteashgupta1** [comment]
Share the video of navbar fix also

**Comment by ANSHIKA-26** [comment]
hey , most of your code is just previous code re -written , its nothing new , also the merge conflicts you have fixed aren't correct , we wont be merging this PR , your code makes the website go bak 2 commits , you did not fix merge conflicts

**Comment by ANSHIKA-26** [comment]
the navbar is completely messed in your PR , even though its fixed now ,if you wish , just raise another issue after learning how more about conflicts and fixing them ! thank you

**Pull request closed without merging**
