### PR TITLE
Fixes #1393 Enhance CSS styles for responsiveness and dark mode adjustments

### LINKED ISSUE #1393: Improving the Feature Post in the footer.
**Is your feature request related to a problem? Please describe.**
Improving the UI of the feature post in the footer in both light and dark mode.

**Describe the solution you'd like**
Making the text more bold and displaying them in the form of small cards which can be opened and closed.
Improving the readability in the light mode.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by harjasae2001**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .

Dark Mode:
image

Light Mode:
image

Responsive:
image

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
image
you some how messed this up , nice footer but kindly fix this

**Comment by harjasae2001** [comment]
I don't get the error. It is working fine in my localhost.
{F0DC4B4B-A8EF-4C2F-8E12-FC90CDC7A6B7}

Can u just share me more details for clarity what's the actual error.

**Comment by ANSHIKA-26** [comment]
check the actual website , its not supposed to look like what your preview shows

**Comment by ANSHIKA-26** [comment]
image
this is what it looks like

**Comment by harjasae2001** [comment]
I'm still not getting the error. Can u pls show me with a video.

**Comment by hiteashgupta1** [comment]
The alignment above the image should look like this
[https://private-user-images.githubusercontent.com/114569262/381669419-29d33f46-818f-42fe-ba0d-6deb80f0701f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODYwOTYsIm5iZiI6MTczMDM4NTc5NiwicGF0aCI6Ii8xMTQ1NjkyNjIvMzgxNjY5NDE5LTI5ZDMzZjQ2LTgxOGYtNDJmZS1iYTBkLTZkZWI4MGYwNzAxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNDQzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGQ2MWYxNWVkM2Q1MTEzMmE5ZjZlZGJlM2Y5MGE1MTQ0MDg2MTA5M2EwZTNjNGQzZDAzNjI4ZmZhZTEyMDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P1NEuXpcb3mUnHISbKh-jOs1hLWY_nbKFKp88-Z7QxM](url)

**Comment by harjasae2001** [comment]
Page not found. 
{C233DF4E-F06A-49C0-8E7F-FA0FD6D62397}

**Comment by hiteashgupta1** [comment]
The alignment above the image should look like this

**Comment by ANSHIKA-26** [comment]
see the leading blog page -
https://word-wise-lithba3rh-anshikas-projects-45924011.vercel.app/blog.html
this is where the CSS is breaking and hence changing the whole design of the page , kindly adjust your CSS code to not change any other files , thank you !

**Comment by ANSHIKA-26** [comment]
closing PR due to no response

**Pull request closed without merging**
