### PR TITLE
Changes made in main.js

### PR DESCRIPTION
**Pull request by Deeptig9138**
Use of const: All constants are declared using const, while let is used only for variables that can change (e.g., in functions).
Simplified Theme Detection: The theme detection logic now uses a single const declaration for the theme, streamlining the logic.
Error Handling: Added checks before manipulating toggle, collapse, and toggleSwitch to avoid errors when elements are not found.
User Controls for Autoplay: Set disableOnInteraction: false in the Swiper configuration, allowing autoplay to continue even after user interaction. You can extend this further by adding buttons to pause/resume autoplay if needed.

### CODE REVIEW

**Comment by Deeptig9138** [comment]
done

**Comment by ANSHIKA-26** [comment]
kindly share relevant screenshots

**Comment by Deeptig9138** [comment]
> kindly share relevant screenshots

screenshot of changes or how it looks when we open it?

**Comment by Deeptig9138** [comment]
i am also done working on readme.md file

**Comment by hiteashgupta1** [comment]
This branch has conflicts that must be resolved

**Comment by Deeptig9138** [comment]
yes doing it now

**Comment by Deeptig9138** [comment]
Screenshot 2024-10-04 143244

**Comment by hiteashgupta1** [comment]
Check fork error in pr
The issue is already resolved

**Pull request closed without merging**
