### PR TITLE
Huge Gap above accordion__wrapper div reduced.

### PR DESCRIPTION
**Pull request by AmanPatre**
I have reduced the gap above accordion__wrapper div . Earlier there was a gap above which was indicating some missing information .
I reduced the gap by reducing the margin-top of container_1 to 60px instead of 500px.

Please merge this contribution.

Before : 

https://github.com/user-attachments/assets/f0f3f88f-613d-41a8-851f-19d8be2e00ae

After : 

https://github.com/user-attachments/assets/f4226a10-f144-4a62-9328-1836a36dc33c

### CODE REVIEW

**Comment by ANSHIKA-26** [comment]
issue number ?

**Comment by AmanPatre** [comment]
#488

**Comment by AmanPatre** [comment]
I dont know what's the issue I created a new PR then also the same issue is arising . I dont know what to do.

**Comment by ANSHIKA-26** [comment]
fixes #488

**Comment by ANSHIKA-26** [comment]
@AmanPatre relax , try to resync  your fork

**Comment by AmanPatre** [comment]
I resynced just now please check

**Comment by AmanPatre** [comment]
Thankyou ❤️

**Pull request merged**
