### PR TITLE
Added short description of wesbite and center align word of day 

### PR DESCRIPTION
**Pull request by AbrerAsif07**
The current website design lacks a short and engaging description for SEO and user engagement. Additionally, the 'Word of the Day' section is not centered, affecting the overall layout and aesthetic of the page.

### Pull Request Checklist

- [ ] I have added screenshots and videos to show before and after the working of my code.
- [ ] I have ensured that the screen size is set to 100% while making the video.
- [ ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ ] I understand that if any the above conditions are not met , my PR will not be MERGED .
Screenshot 2024-10-23 152029

Screenshot 2024-10-23 151959

Screenshot 2024-10-23 153041

### CODE REVIEW

**Comment by hiteashgupta1** [comment]
Kindly follow pr checklist

**Comment by ANSHIKA-26** [comment]
image
remove this

**Comment by AbrerAsif07** [comment]
> Kindly follow pr checklist

What am i MIssing? can you elaborate

**Comment by AbrerAsif07** [comment]
@ANSHIKA-26  made the necessary changes as you described. Pls merge now

**Comment by ANSHIKA-26** [comment]
issue number

**Comment by ANSHIKA-26** [comment]
why is the navbar twice ?
image
and why is word of the day out of its box and why is the word of day box empty ?
image
what exactly did you do ?

**Pull request closed without merging**
