### PR TITLE
Enhanced Navbar Design (Fixes #580)

### LINKED ISSUE #580: Changing Navbar Design
**Describe the bug**
The Navbar design uses an outdated hover effect, and the spacing and alignment of items are inconsistent. The links look cluttered, and the overall visual appeal is diminished due to these issues.

**To Reproduce**
1. Go to the website.
2. Hover over the Navbar links and observe the outdated hover effect.
3. Observe the improper spacing and misalignment of Navbar items.

**Expected behavior**
The Navbar should have a modern, sleek hover effect, such as smooth transitions or subtle highlights. The items should be properly spaced and aligned for a clean, visually appealing design. The Navbar should maintain a balanced layout without any overlapping or uneven spacing.

**Screenshots**

Screenshot 2024-10-06 212825

**Additional context**
The issue may stem from outdated CSS styles or incorrect use of layout classes. Revisiting the CSS for hover effects and item alignment could help modernize the design..

### PR DESCRIPTION
**Pull request by shivam8112005**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .
Before:
Screenshot 2024-10-10 152822
After:
Screenshot 2024-10-10 152724

### CODE REVIEW

**Comment by shivam8112005** [comment]
fixes #580

**Comment by ANSHIKA-26** [comment]
also you messed up the footer somehow , please fix it

**Comment by shivam8112005** [comment]
Ohk i will do that

**Comment by shivam8112005** [comment]
Done?

**Comment by ANSHIKA-26** [comment]
image
why have you added these bg white cards ?

**Comment by shivam8112005** [comment]
i diddnt do anything there

**Comment by ANSHIKA-26** [comment]
why is the footer like this in dark mode ?
image

its perfectly fine in the website right now
image

**Comment by shivam8112005** [comment]
ohk someone used bootstrap classes so when i imported bootstrp css link it gets activated

**Comment by ANSHIKA-26** [comment]
please check the ui of the whole website once , make sure you havent disturbed anything except what you were working on , added a level 3 label for the extra effort ! thanks

**Comment by ANSHIKA-26** [comment]
no rush , just dont mess up anything please

**Comment by ANSHIKA-26** [comment]
although the longer you wait , the more PR merges and the more syncing fork , and code conflicts

**Comment by shivam8112005** [comment]
ohk😅

**Comment by shivam8112005** [comment]
wait 5min

**Comment by shivam8112005** [comment]
hey @ANSHIKA-26  is this ok . from my side i think its done

**Comment by ANSHIKA-26** [comment]
good job

**Comment by anchalchaturvedi08** [comment]
Hello @ANSHIKA-26, I would like to work on this task as well. Could you please assign it to me?

**Pull request merged**
