### PR TITLE
Solved issue no. #661

### PR DESCRIPTION
**Pull request by Mayanksaininh**
### Pull Request Checklist

- [X] I have added screenshots and videos to show before and after the working of my code.
- [X] I have ensured that the screen size is set to 100% while making the video.
- [X] I have synced the latest fork with my local repository and resolved any conflicts.
- [X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X] I understand that if any the above conditions are not met , my PR will not be MERGED .
- 
Screenshot (46)

### CODE REVIEW

**Comment by Mayanksaininh** [comment]
I have refork and resynced
and now I Solved issue number #661 this was assigned to me

**Comment by ANSHIKA-26** [comment]
@Mayanksaininh sync fork please, your fork is very old

**Comment by ANSHIKA-26** [comment]
This branch has conflicts that must be resolved

**Comment by hiteashgupta1** [comment]
Kindly refork and resync

**Pull request closed without merging**
